Repository odoo/odoo, pull requests merged in 2018-07, with the labels that each got.

#25503 [FIX] mrp: Adding a stock move line when creating a raw material
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/views/stock_move_views.xml
Labels: OE

#25499 [FIX] base: properly unlink child views
  odoo/addons/base/ir/ir_ui_view.py
Labels: RD

#25583 [FIX] web: mock fieldsViewGet don't delete raw attrs
  addons/web/static/tests/helpers/mock_server.js
Labels: RD

#25489 Create maulik-raval.md
  doc/cla/individual/maulik-raval.md
Labels: CLA

#25593 [FIX]purchase: A duplicated shipment is not associated with the original PO
  addons/purchase/models/stock.py
Labels: OE

#25292 Master partner screens usability sed
  addons/account/models/partner.py
  addons/account/report/account_invoice_report_view.xml
  addons/account/views/account_view.xml
  addons/account/views/partner_view.xml
  addons/account_analytic_default/views/account_analytic_default_view.xml
  addons/crm/views/res_partner_views.xml
  addons/event/views/event_views.xml
  addons/event/views/res_partner_views.xml
  addons/mail/static/src/js/many2many_tags_email.js
  addons/mail/views/res_partner_views.xml
  addons/mail/wizard/mail_compose_message_view.xml
  addons/payment/models/res_partner.py
  addons/payment/views/res_partner_views.xml
  addons/point_of_sale/views/res_partner_view.xml
  addons/portal/wizard/portal_wizard.py
  addons/portal/wizard/portal_wizard_views.xml
  addons/product/models/res_partner.py
  addons/project/views/res_partner_views.xml
  addons/purchase/views/res_partner_views.xml
  addons/sale/views/res_partner_views.xml
  addons/stock/views/res_partner_views.xml
  addons/survey/wizard/survey_email_compose_message.xml
  addons/website_partner/views/res_partner_views.xml
  odoo/addons/base/views/res_partner_views.xml
  odoo/addons/base/wizard/base_partner_merge_views.xml
Labels: RD

#25621 [FIX] barcodes: documentation in description
  addons/barcodes/README.rst
  addons/barcodes/__manifest__.py
Labels: OE

#25560 [FIX] web: handle onchange on a on2many with an embedded one2many on …
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#25625 [CLA] tanghulu0608
  doc/cla/individual/tanghulu0608.md
Labels: CLA

#25616 [FIX] web: trigger a warning modal when deleting a line while editing…
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/form_tests.js
Labels: OE

#25617 [FIX] base: allow to give a name attribute to the res.parnter copy me…
  odoo/addons/base/res/res_partner.py
Labels: OE

#25626 [FIX] mail: use ids parameter in the process_mail_queue method
  addons/mail/models/mail_mail.py
Labels: OE

#25635 [FIX] base: allow to give a name attribute to the res.groups copy method
  odoo/addons/base/res/res_users.py
Labels: OE

#25628 [FIX] point_of_sale: new session should open with user as cashier
  addons/point_of_sale/static/src/js/models.js
Labels: OE

#25600 [FIX] account: revert reconciled payment with exchange difference entry
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
Labels: OE

#25647 [FIX] website_gengo: adapt JS to v11 editor
  addons/website_gengo/static/src/js/website_gengo.js
Labels: OE

#25683 [FIX] web: remove Work+Sans online font import
  addons/web/views/report_templates.xml
Labels: OE

#25685 [FIX] hr_timesheet: Removing task on a timesheet line
  addons/sale_timesheet/models/account.py
Labels: OE

#25689 [FIX] crm: handle selection fields correctly while merging leads
  addons/crm/models/crm_lead.py
Labels: OE

#25670 Master demo data trigger adt
  addons/sale/data/sale_demo.xml
  addons/web_settings_dashboard/controllers/main.py
  addons/web_settings_dashboard/static/src/js/dashboard.js
  addons/web_settings_dashboard/static/src/xml/dashboard.xml
  odoo/addons/base/__manifest__.py
  odoo/addons/base/data/ir_demo_data.xml
  odoo/addons/base/models/__init__.py
  odoo/addons/base/models/ir_demo.py
  odoo/modules/loading.py
Labels: RD

#25655 [FIX] preserve deactivated taxes on move lines too
  addons/account/models/account_move.py
Labels: Accounting

#25458 [10.0] l10n_fr small improvements to chart of accounts
  addons/l10n_fr/data/account_chart_template_data.xml
Labels: Accounting, Localization

#25741 [FIX] product: variant num w/o prefetch pollution
  addons/product/models/product_template.py
Labels: OE

#25718 [FIX] board: open form view of given action
  addons/board/static/src/js/dashboard.js
  addons/board/static/tests/dashboard_tests.js
Labels: OE

#25713 [DOC] add measure attribute to aggregate
  doc/reference/views.rst
Labels: Framework, RD

#25719 [FIX] web: groupby product on package types triggers a js error
  addons/web/static/src/js/framework/data.js
Labels: OE

#25198 [IMP] Adding a new tag to allow the reporting of non-creditable taxes
  addons/l10n_mx/data/account_tax_data.xml
Labels: Accounting

#25739 [FIX] sale_stock: float division by zero
  addons/sale_stock/models/account_invoice.py
Labels: OE

#25781 [IMP] web: provide a reason for close action
  addons/web/static/src/js/chrome/action_manager.js
  addons/web/static/src/js/core/dialog.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: Framework, RD

#25786 [FIX] stock_account: Automated FIFO error on MO
  addons/stock_account/models/stock.py
Labels: OE

#24854 Import-Export Improvement
  addons/base_import/models/base_import.py
  addons/base_import/security/ir.model.access.csv
  addons/base_import/static/csv/res.partner.csv
  addons/base_import/static/src/js/import_action.js
  addons/base_import/static/src/scss/base_import.scss
  addons/base_import/static/src/xml/base_import.xml
  addons/base_import/tests/test_base_import.py
  addons/crm/models/crm_lead.py
  addons/crm/static/xls/crm_lead.xls
  addons/hr/models/hr.py
  addons/hr/static/xls/hr_employee.xls
  addons/mrp/models/mrp_bom.py
  addons/mrp/static/xls/mrp_bom.xls
  addons/product/__manifest__.py
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/product/static/csv/product.template.csv
  addons/product/static/src/js/product_template_import.js
  addons/product/static/xls/product_pricelist.xls
  addons/product/static/xls/product_supplierinfo.xls
  addons/product/static/xls/product_template.xls
  addons/product/views/product_template_import_templates.xml
  addons/purchase/models/product.py
  addons/purchase/static/xls/product_purchase.xls
  addons/purchase/views/purchase_views.xml
  addons/sale/models/product_template.py
  addons/sale/static/xls/product_pricelist_several.xls
  addons/sale/views/sale_views.xml
  addons/web/controllers/main.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/widgets/data_export.js
  addons/web/static/src/scss/data_export.scss
  addons/web/static/src/xml/base.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/static/xls/res_partner.xls
  requirements.txt
Labels: RD

#25811 [FIX] web_forum: disallow tag editing of questions if karma is unsuff…
  addons/website_forum/views/website_forum.xml
Labels: OE

#25754 Master demo data yti
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/pos_restaurant/data/pos_restaurant_demo.xml
  addons/pos_restaurant/static/img/th-coke.jpg
  addons/pos_restaurant/static/img/th-minute_maid.jpg
  addons/pos_restaurant/static/img/th-water.jpg
  addons/product/data/product_demo.xml
  addons/product/tests/test_product_pricelist.py
  addons/purchase_mrp/__manifest__.py
  addons/purchase_stock/data/purchase_stock_demo.xml
  addons/stock/data/stock_demo2.xml
  addons/stock/models/stock_production_lot.py
  addons/website_sale/data/demo.xml
  addons/website_sale_options/static/src/js/website_sale.test.js
  addons/website_sale_wishlist/static/src/js/website_sale_tour_wishlist.js
Labels: RD

#25721 [FIX] account: reconciliation widget: partial reconcile 2 inv 1 pay
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/tests/reconciliation_tests.js
Labels: OE

#25684 [FIX] l10n_be_invoice_bba: Installation fix the traceback
  addons/l10n_be_invoice_bba/views/res_partner_view.xml
Labels: RD

#25479 [IMP] mail: activity alert
  addons/mail/models/mail_activity.py
  addons/mail/static/src/js/activity.js
  addons/mail/static/src/scss/mail_activity.scss
  addons/mail/static/src/xml/activity.xml
  addons/mail/views/mail_activity_views.xml
Labels: RD

#25802 [FIX] web_editor: display a dialog if posting a translation fails
  addons/web_editor/static/src/js/editor/translator.js
Labels: OE

#17375 [IMP] base_import: binary data should be imported through the url.
  addons/base_import/models/base_import.py
Labels: Framework, RD

#25787 [FIX] base: remove duplicated translation before update
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
Labels: OE

#25710 [DOC] dashboard: add clickable attribute on aggregates
  doc/reference/views.rst
Labels: Framework, RD

#25722 [FIX] web: format value of statinfo widget
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: OE

#25641 [FIX] product_usability: Hide value of the column when the product is…
  addons/product/views/product_views.xml
  addons/stock/views/product_views.xml
Labels: RD

#25634 [IMP]purchase_requisition: Blanket Order: New
  addons/purchase_requisition/data/purchase_requisition_demo.xml
Labels: RD

#25842 [IMP] mail: store activity creator on activity record
  addons/mail/models/mail_activity.py
  addons/mail/static/src/xml/activity.xml
  addons/mail/static/tests/chatter_tests.js
Labels: RD

#25789 [DOC] cmdline,testing: add documentation for test-tags
  doc/reference/cmdline.rst
  doc/reference/testing.rst
  odoo/tests/common.py
Labels: RD

#24311 [IMP] repair - display description
  addons/repair/models/repair.py
Labels: RD

#25751 [FIX]base: set high priority to the main partner form view to open it…
  odoo/addons/base/views/res_partner_views.xml
Labels: RD

#25759 [ADD] web: easy to change noupdate value
  addons/web/static/src/js/widgets/debug_manager.js
  addons/web/static/src/xml/base.xml
  odoo/addons/base/models/ir_model.py
Labels: RD, Wishlist

#25961 opening balances tree view: highight accounts whose opening balance has been set
  addons/account/wizard/setup_wizards_view.xml
Labels: Accounting, RD

#25963 [FIX] website_hr_recruitment: frontend creation ok
  addons/website_hr_recruitment/controllers/main.py
Labels: OE

#25749 [FIX] survey: fix context filter
  addons/survey/views/survey_views.xml
Labels: RD

#25736 [sign] Improve popup + add selection field type on signatures
  addons/web/models/models.py
Labels: RD

#24661 Master project onboarding improvements sjo
  addons/project/static/src/js/tour.js
  addons/project/views/project_views.xml
Labels: RD

#20517 Master mrp hide variants column in bom jao
  addons/mrp/models/mrp_bom.py
  addons/mrp/views/mrp_bom_views.xml
Labels: Logistics, RD

#25998 [FIX] web: edited password fields should not contain '*'
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/views/form_tests.js
Labels: Confirmed, Framework, RD

#26019 [FIX] base: use -U+FEFF instead of U+2011 in -num
  openerp/addons/base/ir/ir_qweb.py
  openerp/addons/test_converter/tests/test_html.py
Labels: OE

#26025 [FIX] web: empty input for empty password field
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: Framework, RD

#25518 [FIX] P3: add missing opcode
  odoo/tools/safe_eval.py
Labels: OE

#26043 [FIX] im_livechat: bad rating=1 not 0 w/ 75d3121c
  addons/im_livechat/static/src/js/im_livechat.js
Labels: OE

#26047 [FIX] im_livechat: double click on :) => 1 message
  addons/im_livechat/static/src/js/im_livechat.js
Labels: OE

#25677 [IMP] Portal: activate B2C portal by default
  addons/auth_signup/data/auth_signup_data.xml
Labels: RD
