Repository odoo/odoo, pull requests merged in 2018-10, with the labels that each got.

#27148 [FIX] web: debug_manager set defaults
  addons/web/static/src/js/widgets/debug_manager.js
  addons/web/static/tests/widgets/debug_manager_tests.js
Labels: OE

#27241 [FIX] sale_mrp: price unit of kit
  addons/sale_mrp/sale_mrp.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
Labels: OE

#27344 [FIX] delivery: new error message
  addons/delivery/views/delivery_view.xml
Labels: RD

#27351 [imp] hw_scale: Disable Adam if not used
  addons/hw_scale/controllers/main.py
Labels: RD

#27370 [FIX] base: compare on original module
  odoo/addons/base/models/ir_model.py
Labels: RD

#27347 [FIX] sale_crm: quotes count
  addons/sale_crm/views/crm_lead_views.xml
  addons/sale_crm/views/sale_order_views.xml
Labels: OE

#27376 [FIX] stock: decrease initial demand quantity
  addons/stock/views/stock_picking_views.xml
Labels: OE

#27379 [FIX] stock: decrease initial demand quantity
  addons/stock/views/stock_picking_views.xml
Labels: OE

#27305 [FIX] hw_escpos: Printing Cyrillic symbols
  addons/hw_escpos/escpos/escpos.py
Labels: RD

#27392 [FIX] stock_account: return dropship
  addons/stock_account/models/stock.py
Labels: OE

#27473 [FIX] Corrected Icon for Cancel Button
  addons/account_cancel/views/account_views.xml
Labels: error 🙅, seen 🙂

#27428 [FIX] mail: sudo on user name
  addons/mail/models/mail_tracking_value.py
  addons/mail/views/mail_templates.xml
Labels: OE

#27545 [FIX] web: fetch dependency fields in x2many
  addons/web/static/src/js/views/basic/basic_view.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: RD

#27576 [FIX] web_editor: Not possible to edit a link on safari
  addons/mass_mailing/static/src/less/themes/theme_default.less
  addons/web_editor/static/src/less/web_editor.ui.less
Labels: OE

#27607 [FIX] delivery: translate delivery name
  addons/delivery/models/sale_order.py
Labels: OE

#27623 [FIX] tools: expand user and vars for data_dir
  odoo/tools/config.py
Labels: RD

#27616 [FIX] calendar: notifications may appear
  addons/calendar/static/src/js/base_calendar.js
  addons/web/static/src/js/services/notification_service.js
  addons/web/static/tests/services/notification_service_tests.js
Labels: RD

#27618 [I18N] calendar: correct bad email template translation
  addons/calendar/i18n/fr.po
Labels: OE

#27704 [FIX] sale_stock: return of return and delivered quantity
  addons/sale_stock/models/sale_order.py
Labels: OE

#27543 [FIX] account: fix clause on accounts in reconciliation widget
  addons/account/models/account_bank_statement.py
Labels: Accounting, RD

#27728 [FIX] mrp: bom structure in batch
  addons/mrp/report/mrp_report_bom_structure.py
Labels: RD

#27787 [FIX] stock: incorrect translation
  addons/stock/i18n/de.po
  addons/stock/i18n/fr.po
Labels: OE

#27259 Create zoggy444.md
  doc/cla/individual/zoggy444.md
Labels: CLA

#27795 [FIX] auth_signup: invalid value on field signup_valid for non superuser
  addons/auth_signup/models/res_partner.py
Labels: RD

#27399 [FIX] base: renaming of x2many fields
  odoo/addons/base/models/ir_model.py
Labels: RD

#27733 [FIX] mail: add test for concurrent updates on notifications
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_race.py
Labels: RD

#27886 [Fix] point_of_sale: Button spamming create duplicates
  addons/point_of_sale/static/src/js/screens.js
Labels: OE

#28003 [FIX] migration doc
  odoo/modules/migration.py
Labels: Documentation

#28018 [FIX] delivery: wrong currency conversion
  addons/delivery/models/sale_order.py
Labels: OE

#27936 [FIX] point_of_sale: IoT https in pos
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/devices.js
  addons/point_of_sale/static/src/js/models.js
Labels: 10.0, 11.0, 12.0, Point of Sale, RD

#28147 [FIX] mrp: workorders of sub-BOMs
  addons/mrp/models/mrp_production.py
Labels: OE

#26820 [Fix] sale : make same field appears only once when trying to define …
  addons/sale/static/src/js/sale.js
  addons/sale/static/tests/sales_team_dashboard_tests.js
  addons/sale/views/assets.xml
Labels: RD

#28238 [FIX] website_links: do not require flash to copy text to clipboard
  addons/website_links/static/src/js/website_links.js
  addons/website_links/views/website_links_template.xml
Labels: OE

#28247 [FIX] base: subscribe new API onchange methods for module fields
  odoo/addons/base/res/res_config.py
Labels: RD

#28272 [FIX] account_budget: properly calculate percentage sum in read_group
  addons/account_budget/models/account_budget.py
Labels: Accounting, OE
