Repository odoo/odoo, pull requests merged in 2018-06, with the labels that each got.

#24999 [FIX] website_sale: performance with carousel
  addons/website_sale/views/templates.xml
Labels: OE

#23877 [IMP] base: allow to move an element in inherited view
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: RD

#25013 [FIX] stock: assign move
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
Labels: OE

#24966 [FIX] website_event: unblock button when no reserve
  addons/website_event/static/src/js/website_event.js
Labels: OE

#24991 [FIX] website_event: unblock button when no reserve
  addons/website_event/static/src/js/website_event.js
Labels: OE

#25021 [FIX] stock: Stock Level Forecast
  addons/stock/report/report_stock_forecast.py
Labels: OE

#24953 [FIX] point_of_sale: pos_config write should be @multi compliant
  addons/point_of_sale/models/pos_config.py
Labels: RD

#25040 [FIX] stock_account: do not display to_refund on return picking as to…
  addons/stock_account/views/stock_account_views.xml
Labels: OE

#24946 [FIX] child_of False
  odoo/addons/base/tests/test_expression.py
  odoo/osv/expression.py
Labels: RD

#25036 [FIX] mass_mailing: unsubscribe if trailing '/'
  addons/mass_mailing/models/mail_mail.py
Labels: OE

#25049 [FIX] delivery: tracking reference
  addons/delivery/models/stock_picking.py
Labels: OE

#24610 [FIX] pos: reconciliation and performance issues
  addons/point_of_sale/models/pos_session.py
Labels: OE

#25064 [FIX] base: timeout on smtp connections
  openerp/addons/base/ir/ir_mail_server.py
Labels: OE

#24817 [FIX] crm: Access rights issues in contact merging
  addons/crm/base_partner_merge.py
Labels: RD

#25095 [FIX] mass_mailing: URI too long
  addons/mass_mailing/static/src/js/mass_mailing.js
Labels: OE

#21921 Master mailman clone dam5
  addons/mail/__manifest__.py
  addons/mail/controllers/main.py
  addons/mail/data/ir_cron_data.xml
  addons/mail/data/mail_data.xml
  addons/mail/models/__init__.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_company.py
  addons/mail/models/res_users.py
  addons/mail/security/ir.model.access.csv
  addons/mail/security/mail_security.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/services/chat_manager.js
  addons/mail/static/src/js/thread.js
  addons/mail/static/src/xml/discuss.xml
  addons/mail/static/src/xml/thread.xml
  addons/mail/static/tests/discuss_moderation_tests.js
  addons/mail/static/tests/discuss_tests.js
  addons/mail/views/mail_channel_views.xml
  addons/mail/views/mail_message_views.xml
  addons/mail/views/mail_moderation_views.xml
  addons/mail/views/mail_templates.xml
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/common.py
  addons/test_mail/tests/test_mail_channel.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_res_users.py
Labels: RD

#24897 [FIX] stock, stock_account: valuation with owner
  addons/stock/models/product.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
Labels: OE

#25120 [FIX] website_livechat: use only consumed ratings
  addons/website_livechat/controllers/main.py
Labels: OE

#25121 [FIX] board: add extra info
  addons/board/i18n/board.pot
  addons/board/static/src/js/favorite_menu.js
Labels: OE

#25131 [FIX] portal: typo in domain portal_message_fetch
  addons/portal/controllers/mail.py
Labels: OE

#25132 [FIX] purchase: qty updated
  addons/purchase/views/purchase_template.xml
Labels: OE

#25101 [FIX] account: in account config, constrain exchange diff journal's d…
  addons/account/models/res_config.py
Labels: OE

#25074 [FIX] mail: open a channel in discuss on systray click
  addons/mail/static/src/js/systray.js
Labels: OE

#24321 Master hr recruitment y u no haz kanban state mao
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/static/src/scss/hr_job.scss
  addons/hr_recruitment/views/hr_recruitment_views.xml
Labels: RD

#25160 [IMP] web: add decoration support for all field widgets
  addons/web/static/src/js/fields/abstract_field.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/basic/basic_view.js
  addons/web/static/src/scss/list_view.scss
  addons/web/static/src/scss/webclient.scss
  addons/web/static/tests/views/form_tests.js
  doc/reference/javascript_reference.rst
Labels: RD

#24959 [IMP] fleet: Allow to search vehicles based on assignation logs
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/views/fleet_vehicle_views.xml
Labels: RD

#24169 Master activity usability tde
  addons/calendar/views/mail_activity_views.xml
Labels: RD

#25054 [FIX] event: print time on badge using the event timezone
  addons/event/report/event_event_templates.xml
Labels: OE

#25153 [FIX] payment_authorize: state code
  addons/payment_authorize/models/payment.py
Labels: OE

#25149 [FIX] mrp_repair: return move with owner
  addons/mrp_repair/models/mrp_repair.py
Labels: OE

#25158 [FIX] point_of_sale: prevent product unlink
  addons/point_of_sale/models/product.py
Labels: OE

#25161 [FIX] point_of_sale: refresh when qty changed
  addons/point_of_sale/static/src/js/models.js
Labels: OE

#25127 [FIX] odoo: copy_translation translates the wrong view
  odoo/models.py
Labels: OE

#25088 [FIX] base: rng common def: js_class must be included
  odoo/addons/base/rng/tree_view.rng
Labels: OE

#24593 Master timesheet plan jem
  addons/sale_timesheet/controllers/main.py
  addons/sale_timesheet/report/project_profitability_report_analysis.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_reporting.py
  addons/sale_timesheet/views/hr_timesheet_templates.xml
Labels: RD

#25179 Master package pim
  addons/delivery/models/stock_picking.py
  addons/delivery/views/delivery_view.xml
  addons/stock/__manifest__.py
  addons/stock/models/__init__.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_package_level.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/stock/security/ir.model.access.csv
  addons/stock/tests/test_move2.py
  addons/stock/tests/test_packing.py
  addons/stock/views/stock_move_line_views.xml
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_package_level_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/stock/views/stock_quant_views.xml
  addons/stock_dropshipping/tests/test_lifo_price.py
Labels: RD

#24866 [FIX] mrp, stock: Duplicate Detailed Operations
  addons/mrp/models/stock_move.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
Labels: OE

#25186 [FIX] base: Avoid exception when showing error in namespaced qweb node
  odoo/addons/base/ir/ir_qweb/qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: OE

#25070 [FIX] #13544. move barcode view definition from point_of_sale into base module
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/views/res_partner_view.xml
  odoo/addons/base/views/res_partner_views.xml
Labels: Point of Sale

#25146 [FIX] base: depends if no depends is ()
  odoo/addons/base/ir/ir_model.py
  odoo/addons/test_new_api/tests/test_new_fields.py
Labels: OE

#25207 [FIX] base: P3.5 - P3.6 compatibility
  odoo/addons/base/tests/test_qweb.py
Labels: RD

#25133 [IMP] payment_ogone: Avoid requesting already owned data from Ogone
  addons/payment_ogone/controllers/main.py
Labels: RD

#25150 [IMP] pos_restaurant: possibility to redefine new buttons and screens
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/pos_restaurant/static/src/js/notes.js
  addons/pos_restaurant/static/src/js/printbill.js
  addons/pos_restaurant/static/src/js/splitbill.js
Labels: Point of Sale

#25187 [FIX] web_editor: link don't duplicate child text
  addons/web_editor/static/lib/summernote/src/js/module/Editor.js
  addons/web_editor/static/src/js/widgets.js
Labels: OE

#25219 [FIX] stock: Printing barcode on picking list
  addons/stock/report/report_stockpicking_operations.xml
Labels: OE

#25058 [WIP][FIX] stock: partial reserve in MTO
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
Labels: OE

#25116 [FIX]point_of_sale: change method name of point of sale as it is same…
  addons/point_of_sale/models/res_config_settings.py
Labels: RD

#25218 [FIX] website_event: allow controller to read event.registration
  addons/website_event/controllers/main.py
Labels: RD

#24724 [FIX]crm_project: traceback has been fixed while converting lead to task
  addons/mail/models/mail_thread.py
Labels: RD

#24940 [FIX] website_sale: unpaid orders and abandoned carts are not open th…
  addons/website_sale/views/sale_order_views.xml
Labels: RD

#25225 [FIX] event: use groups to hide event count stat button
  addons/event/views/res_partner_views.xml
Labels: RD

#25247 [FIX] website: valid time zone guessed from GeoIP
  addons/website/models/ir_http.py
Labels: 9.0, RD

#25249 [FIX] hr_holidays: avoid execution of onchange when no employee linked
  addons/hr_holidays/models/hr_leave.py
Labels: RD

#25244 [FIX] event: event stat button
  addons/event/models/res_partner.py
Labels: OE

#25250 [FIX] mrp: register time on WO
  addons/mrp/views/mrp_workorder_views.xml
Labels: OE

#23621 [REM] fetchmail: remove action_id on fetchmail
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail/views/fetchmail_views.xml
Labels: RD

#25269 [FIX] base_address_extended: NL street format
  addons/base_address_extended/__manifest__.py
  addons/base_address_extended/data/base_address_extended_data.xml
Labels: OE

#25261 [FIX] web: no drop invalid record in list on discard
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: 11.0, Framework, OE, RD

#25262 [FIX] mail: warn user on record reload before post message
  addons/mail/static/src/js/chatter.js
  addons/mail/static/src/js/chatter_composer.js
  addons/mail/static/tests/chatter_tests.js
Labels: Framework, OE, RD

#24766 [IMP] stock,uom: improve constraint messages
  addons/stock/models/product.py
  addons/uom/models/uom_uom.py
Labels: RD

#25274 [FIX] point_of_sale: modify tax
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_tax.py
Labels: OE

#25264 [FIX] web: enable button at end of action
  addons/web/static/src/js/chrome/action_manager.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: OE

#25315 [FIX] stock_account, stock_dropshipping: do not change accounts
  addons/stock_account/data/stock_account_data_post_install.yml
  addons/stock_dropshipping/tests/test_stockvaluation.py
Labels: OE

#25316 [FIX] stock_account: inventory valuation
  addons/stock_account/models/product.py
Labels: OE

#25331 [FIX] l10n_ch: default tax
  addons/l10n_ch/data/account_vat2011_data.xml
Labels: OE

#24904 [FIX] web_editor: convert link to send by email
  addons/web_editor/static/src/js/editor/transcoder.js
Labels: RD

#25350 [FIX] product: bring back description in product views
  addons/product/views/product_views.xml
Labels: RD

#25335 [FIX] stock: inventory security with translation
  addons/stock/models/stock_inventory.py
Labels: OE

#25345 [FIX] resource: 24h shift
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
Labels: Blocked, OE

#25356 [FIX] sale_timesheet: SO line on subtask
  addons/sale_timesheet/models/project.py
Labels: OE

#25378 [FIX] point_of_sale, sale_mrp, sale_stock: sort moves
  addons/point_of_sale/models/pos_order.py
  addons/sale_mrp/models/sale_mrp.py
  addons/sale_stock/models/account_invoice.py
Labels: OE

#25376 [FIX] sale_mrp, sale_stock: sort moves
  addons/sale_mrp/sale_mrp.py
  addons/sale_stock/models/account_invoice.py
Labels: OE

#25374 [FIX] sale_mrp, sale_stock: sort moves
  addons/sale_mrp/sale_mrp.py
  addons/sale_stock/sale_stock.py
Labels: OE

#25353 [FIX] stock_account: product on AML
  addons/stock_account/models/product.py
Labels: OE

#25358 [FIX] barcodes: nomenclature
  addons/barcodes/static/src/js/barcode_parser.js
Labels: OE

#25180 [FIX] web: actions target=new should transmit their on_close
  addons/web/static/src/js/chrome/action_manager.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: OE

#25396 [FIX] point_of_sale: settings access
  addons/point_of_sale/views/point_of_sale_dashboard.xml
Labels: OE

#25393 [FIX] mass_mailing_event: stat button overlap
  addons/mass_mailing_event/i18n/mass_mailing_event.pot
  addons/mass_mailing_event/views/event_views.xml
Labels: OE

#25325 [FIX] web: disable Save button
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/tests/views/form_tests.js
Labels: OE

#25419 [FIX] auth_signup: do not send email to duplicated user
  addons/auth_signup/models/res_users.py
Labels: OE

#25454 [FIX] website_sale_options: prevent double-click
  addons/website_sale_options/static/src/js/website_sale.js
Labels: OE

#25457 [FIX] base: default value in `set_multi`
  odoo/addons/base/res/ir_property.py
Labels: OE

#25439 [FIX] addons: no unsubscribe for unsubscribed
  addons/website_mail_channel/static/src/js/website_mail_channel.snippet.js
Labels: OE

#25478 [FIX] mail: Playing video not working on iOS
  addons/mail/models/mail_message.py
Labels: OE

#25492 [FIX] mrp: BOM Cost quantity format
  addons/mrp/report/mrp_bom_cost_report_templates.xml
Labels: OE

#25496 [FIX] base: print multi record report no outlines
  odoo/addons/base/ir/ir_actions_report.py
Labels: OE

#25068 [FIX] google_account: backport of c444b5a293
  addons/google_account/google_account.py
Labels: OE

#25501 [FIX] sale: invoice template
  addons/sale/i18n/sale.pot
  addons/sale/report/invoice_report_templates.xml
Labels: OE

#23777 [IMP] http: Sessions implicit deactivation
  addons/auth_crypt/auth_crypt.py
  addons/auth_oauth/res_users.py
  addons/web/controllers/main.py
  openerp/addons/base/res/res_users.py
  openerp/http.py
  openerp/service/security.py
  openerp/tests/common.py
Labels: RD

#25510 [FIX] stock: search route name
  addons/stock/views/stock_location_views.xml
Labels: OE

#25507 [FIX] mail: smiley on several lines chrome
  addons/mail/static/src/less/composer.less
Labels: OE

#25476 [FIX] Bad layout for button Published
  addons/web/static/src/scss/ui.scss
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website/views/website_navbar_templates.xml
Labels: RD

#25481 [FIX] Remove bad aria-hidden
  addons/account/views/account_portal_templates.xml
  addons/account_payment/views/account_portal_templates.xml
  addons/website/views/website_templates.xml
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_membership/views/website_membership_templates.xml
  addons/website_quote/views/website_quote_templates.xml
  odoo/addons/base/views/res_users_views.xml
Labels: RD

#25524 [FIX] account: batch deposit in reconcile uncut
  addons/account/static/src/less/account_reconciliation.less
Labels: OE

#25527 [FIX] website_sale_wishlist: prevent adding to cart
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
Labels: OE
