Repository odoo/odoo, pull requests merged in 2018-02, with the labels that each got.

#22550 [REF] mail: make related activity_date_deadline not stored
  addons/mail/models/mail_activity.py
  addons/test_mail/tests/test_performance.py
Labels: RD

#22846 [IMP] crm: show currency symbol in quick create form
  addons/crm/views/crm_lead_views.xml
Labels: RD

#22914 [FIX] mail,web: JS mail and services tracebacks
  addons/account/static/tests/reconciliation_tests.js
  addons/bus/static/src/js/services/bus_service.js
  addons/im_livechat/static/src/js/im_livechat.js
  addons/mail/static/src/js/composer.js
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/extended_chat_window.js
  addons/mail/static/src/js/services/chat_manager.js
  addons/mail/static/src/js/services/chat_window_manager.js
  addons/mail/static/src/js/systray.js
  addons/mail/static/src/js/thread_field.js
  addons/mail/static/tests/chat_window_tests.js
  addons/mail/static/tests/chatter_tests.js
  addons/mail/static/tests/discuss_mobile_tests.js
  addons/mail/static/tests/helpers/test_utils.js
  addons/mail/static/tests/systray_tests.js
  addons/web/static/src/js/chrome/abstract_web_client.js
  addons/web/static/src/js/chrome/root_widget.js
  addons/web/static/src/js/core/abstract_service.js
  addons/web/static/src/js/core/registry.js
  addons/web/static/src/js/core/service_mixins.js
  addons/web/static/src/js/core/utils.js
  addons/web/static/src/js/services/ajax_service.js
  addons/web/static/src/js/services/core.js
  addons/web/static/src/js/services/local_storage_service.js
  addons/web/static/src/js/services/report_service.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/helpers/test_utils.js
  addons/web/static/tests/views/view_dialogs_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/static/src/js/iframe.js
  addons/web_tour/static/src/js/tour_service.js
  addons/website/static/src/js/content/website_root.js
  addons/website_slides/static/src/js/slides.js
Labels: Framework, RD

#23009 [FIX] web_editor: error on cross domain stylesheet
  addons/web_editor/static/src/js/transcoder.js
  addons/web_editor/static/src/js/widgets.js
Labels: OE

#22836 [FIX] point_of_sale, stock_account: POS Anglo-Saxon Accounting
  addons/account/models/account_invoice.py
  addons/point_of_sale/__init__.py
  addons/point_of_sale/point_of_sale.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/stock_account/stock_account.py
Labels: OE

#22938 [FIX] project: set as favorite
  addons/project/models/project.py
  addons/project/tests/test_access_rights.py
  addons/project/views/project_views.xml
Labels: OE

#22926 [FIX] project: follow stage change
  addons/project/models/project.py
Labels: OE

#20485 [survey] remove dependency to website
  addons/survey/__manifest__.py
  addons/survey/controllers/main.py
  addons/survey/models/survey.py
  addons/survey/views/survey_result.xml
  addons/survey/views/survey_templates.xml
  addons/survey/views/survey_views.xml
  addons/website_survey/__init__.py
  addons/website_survey/__manifest__.py
  addons/website_survey/views/website_survey_templates.xml
Labels: RD

#22491 [IMP] Resource: Expand testing on timezones
  addons/resource/tests/test_resource.py
Labels: RD

#21759 Master hr holidays improve leave type rli
  addons/hr_holidays/data/hr_holidays_data.xml
  addons/hr_holidays/models/hr.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_holidays_flow.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
Labels: RD

#23037 [FIX] stock: UserError message improvement
  addons/stock/models/product.py
Labels: OE

#23085 [REV] crm: allow a user assigned to activity to see lead
  addons/crm/security/crm_security.xml
Labels: OE

#23090 Remove empty description & keyword metas
  addons/website/views/website_templates.xml
Labels: OE

#22646 [IMP] chatter: add settings button on channels
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/less/discuss.less
  addons/mail/static/src/xml/discuss.xml
Labels: RD

#22751 Not able post rating
  addons/portal/static/src/js/portal_chatter.js
Labels: RD

#23038 Don't fold M2M at export when not in import compatible mode
  addons/web/controllers/main.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: OE

#23028 Avoid early recomputes during unlink
  odoo/models.py
Labels: OE

#23113 Create osarrat.md
  doc/cla/individual/osarrat.md
Labels: CLA

#22494 Fix high memory usage in export
  odoo/models.py
Labels: RD

#22946 [CLA] ADD: New team member
  doc/cla/individual/willmakenoise.md
Labels: CLA

#23145 [FIX] hr_holidays: Remove related on employee's department
  addons/hr_holidays/models/hr.py
  addons/hr_holidays/models/hr_holidays.py
Labels: RD

#22889 [FIX] purchase, sale_stock: propagation of UOM
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_create_picking.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
Labels: RD

#23153 [FIX] mail: IP domain name when linkifying
  addons/mail/static/src/js/utils.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/mail/views/mail_templates.xml
Labels: OE

#23164 [FIX] web_editor: don't format xml with script tag
  addons/web_editor/static/src/js/widgets/ace.js
Labels: OE

#23177 [FIX] base: copy VAT
  odoo/addons/base/res/res_partner.py
Labels: OE

#23147 [MERGE] mail,web: various JS mail fixes
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/services/chat_manager.js
  addons/mail/static/src/js/services/chat_window_manager.js
  addons/mail/static/tests/chatter_tests.js
  addons/mail/static/tests/discuss_mobile_tests.js
  addons/mail/static/tests/discuss_tests.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/static/tests/helpers/test_utils.js
  addons/mail/views/mail_templates.xml
  addons/web/static/tests/helpers/test_utils.js
Labels: RD

#23067 [FIX] stock: immediate transfer and unreserved move
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/stock/wizard/stock_immediate_transfer.py
Labels: OE

#23186 [IMP] account: payment receipt translation
  addons/account/report/account_report_payment_receipt_templates.xml
Labels: OE

#21761 [FIX] payment: Payment form not implemented on /website_payment/pay
  addons/payment/controllers/portal.py
  addons/payment/static/src/js/payment_transaction_portal.js
  addons/payment/views/payment_portal_templates.xml
  addons/payment_stripe/static/src/js/stripe.js
Labels: RD

#23190 [FIX] stock: validate picking in waiting state
  addons/stock/models/stock_picking.py
Labels: OE

#16040 [FIX] mail: know who added somebody to the channel
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
Labels: RD

#23193 [FIX] stock_account: method expect a record, not an id
  addons/stock_account/stock_account.py
Labels: OE

#23218 [FIX] stock: check the state before put in pack
  addons/stock/models/stock_picking.py
Labels: OE

#23202 [FIX] stock: extra move, backorder and unit price
  addons/purchase/tests/test_stockvaluation.py
  addons/stock/models/stock_move.py
Labels: RD

#23222 [FIX] mail: tracking of custom field
  addons/mail/models/ir_model.py
Labels: OE

#23228 [FIX] stock_account: apply ir rules
  addons/stock_account/report/stock_history.py
Labels: OE

#23225 [FIX] mail: no view edit on forum link in notif
  addons/mail/static/src/js/thread.js
Labels: OE

#23231 [FIX] stock_account: groupby
  addons/stock_account/report/stock_history.py
Labels: OE

#21724 [FIX] web: evaluation of xml templates must be retro compatible
  addons/web/static/src/js/core/domain.js
Labels: RD

#23235 [FIX] crm: link in planner
  addons/crm/data/web_planner_data.xml
Labels: OE

#23213 [FIX] point_of_sale: do not recompute manually set prices
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/screens.js
  addons/point_of_sale/static/src/js/tests.js
Labels: 11.0, OE

#23251 [FIX] pos_discount: fallback default value
  addons/pos_discount/models/pos_config.py
Labels: OE

#23253 [FIX] pos_discount: error if misconfigured product
  addons/pos_discount/i18n/pos_discount.pot
  addons/pos_discount/static/src/js/discount.js
Labels: OE

#23224 [FIX] account: Register a partial payment as fully paid
  addons/account/models/account_payment.py
  addons/account/tests/test_payment.py
Labels: OE

#23264 [FIX] l10n_in_hr_payroll: spelling mistake
  addons/l10n_in_hr_payroll/data/l10n_in_hr_payroll_data.xml
Labels: OE

#23263 [FIX] hr_payroll, resource: no attendances
  addons/hr_payroll/models/hr_payslip.py
  addons/resource/models/resource_mixin.py
Labels: OE

#22849 [IMP] mail: Discuss inside alignment 'Add a channel' field with a cha…
  addons/mail/static/src/less/discuss.less
Labels: RD

#23268 [FIX] sale_timesheet: format amount
  addons/sale_timesheet/views/hr_timesheet_templates.xml
Labels: OE

#23286 [FIX] sale: re-init account.invoice.report view
  addons/sale/__init__.py
Labels: RD

#23288 [FIX] mail: rotate image in preview
  addons/mail/static/src/js/document_viewer.js
  addons/mail/static/src/less/composer.less
  addons/mail/static/src/xml/thread.xml
Labels: OE

#23233 [IMP] account: allow partial reconciliation with write-off
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/tests/reconciliation_tests.js
Labels: OE

#22910 [IMP] purchase_requisition : the field analytic account is already on…
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/views/purchase_requisition_views.xml
Labels: RD

#22265 [FIX] stock: remove existing demo data on reinstall
  addons/stock/__init__.py
  addons/stock/__manifest__.py
Labels: RD

#22012 [FIX] base_import_module: don't assume data/ exists
  addons/base_import_module/models/ir_module.py
Labels: RD

#23329 [CLA] Sign CLA for p-tombez
  doc/cla/corporate/camptocamp.md
Labels: CLA

#23295 Create aymanadam5.md
  doc/cla/individual/aymanadam5.md
Labels: CLA

#23294 [IMP][TMP] rating: do not store rating value on message
  addons/rating/models/mail_message.py
  addons/rating/models/mail_thread.py
  addons/test_mail/tests/test_performance.py
Labels: RD

#23267 [FIX] mail: use correct emoji for shortcode
  addons/mail/data/mail_shortcode_data.xml
  addons/mail/static/src/img/smiley/smile_open_mouth.png
Labels: RD, Services

#23191 Correct filters on invoices V11
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_invoice_view.xml
  addons/account/views/account_journal_dashboard_view.xml
Labels: OE, RD

#23342 [FIX] account: link bank to partner
  addons/account/models/account_bank_statement.py
Labels: OE

#23332 [FIX] product: create_variant forward-port 5c2380e
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
Labels: OE

#23338 [CLA] apesquero CLA
  doc/cla/individual/apesquero.md
Labels: CLA

#23285 [FIX] base: Do not force creating localhost SMTP server
  openerp/addons/base/base_data.xml
Labels: 9.0, Services

#22554 [doc] add missing params and profiling
  doc/howtos/profile/flamegraph.svg
  doc/howtos/profilecode.rst
  doc/reference/cmdline.rst
  doc/setup/deploy.rst
  doc/tutorials.rst
  doc/webservices.rst
Labels: RD

#23157 [FIX] ir.cron : prevent unallowed launch by rpc
  odoo/addons/base/ir/ir_cron.py
Labels: 11.0, Framework

#23355 [FIX] base_import: allow whitespace in empty float
  addons/base_import/models/base_import.py
Labels: OE

#23347 [FIX] sale: sale_count
  addons/sale/models/product_product.py
  addons/sale/views/sale_views.xml
  addons/sale_stock/views/stock_views.xml
Labels: OE

#21282 [FIX] account: dummy_account_id should be readonly
  addons/account/models/account_move.py
Labels: Accounting

#23343 [FIX] stock: Wrong production/scrap/adjustment location used in multi-company
  addons/stock/models/stock_scrap.py
Labels: OE

#23226 [FIX] purchase: orderpoint should redirect to linked PO
  addons/purchase/models/stock.py
  addons/purchase/views/stock_views.xml
Labels: RD

#23373 [FIX] project: kanban needaction link well shown
  addons/project/static/src/less/project_dashboard.less
  addons/project/views/project_views.xml
Labels: OE

#23382 [FIX] crm: change email alias
  addons/crm/models/res_config_settings.py
Labels: OE
