Repository odoo/odoo, pull requests merged in 2018-08, with the labels that each got.

#26081 [FIX] mass_mailing_event: keep default domain
  addons/mass_mailing_event/models/__init__.py
  addons/mass_mailing_event/models/mass_mailing.py
Labels: OE

#26097 [FIX] base: set currency on a new db
  odoo/service/db.py
Labels: OE

#25989 [REF] point of sale: revert wrong configuration change
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/res_company.py
  addons/point_of_sale/models/res_config_settings.py
  addons/point_of_sale/views/pos_config_view.xml
  addons/point_of_sale/views/res_config_settings_views.xml
Labels: RD

#26082 [FIX] account: Wrong payment amount in multi-currency
  addons/account/models/account_payment.py
Labels: OE

#25602 Master sale services jem
  addons/account/models/account_invoice.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/views/project_views.xml
  addons/sale/models/sale.py
  addons/sale/report/sale_report.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_timesheet/controllers/main.py
  addons/sale_timesheet/data/sale_service_demo.xml
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/account_invoice.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/report/project_profitability_report_analysis.py
  addons/sale_timesheet/static/src/scss/sale_timesheet.scss
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_reporting.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/sale_timesheet/tests/test_timesheet_revenue.py
  addons/sale_timesheet/views/hr_timesheet_templates.xml
  addons/sale_timesheet/views/hr_timesheet_views.xml
  addons/sale_timesheet/views/project_task_views.xml
Labels: RD, Services

#26140 [FIX] website_sale_digital: Consider only portal files as digital pro…
  addons/website_sale_digital/controllers/main.py
Labels: RD

#26099 [FIX]base : Correct the typo.
  addons/mail/data/mail_channel_demo.xml
  addons/stock/wizard/stock_scheduler_compute.py
  addons/web/static/src/xml/base.xml
Labels: RD

#26154 [IMP] l10n_be_invoice_bba: make structured comm working per company, not partner
  addons/l10n_be_invoice_bba/__manifest__.py
  addons/l10n_be_invoice_bba/models/__init__.py
  addons/l10n_be_invoice_bba/models/account_invoice.py
  addons/l10n_be_invoice_bba/models/res_company.py
  addons/l10n_be_invoice_bba/models/res_config_settings.py
  addons/l10n_be_invoice_bba/models/res_partner.py
  addons/l10n_be_invoice_bba/views/res_config_settings_views.xml
  addons/l10n_be_invoice_bba/views/res_partner_view.xml
Labels: Accounting, RD

#26159 [FIX] crm: enable customizable pipeline action
  addons/crm/models/crm_team.py
Labels: OE

#26176 [FIX] stock, purchase: clean moves to merge
  addons/purchase/models/stock.py
  addons/stock/models/stock_move.py
Labels: OE

#26160 [FIX] purchase: Receive Products ok context F5
  addons/purchase/models/purchase.py
Labels: OE

#26119 [FIX] mrp_repair: Access Rights for stock user
  addons/mrp_repair/security/ir.model.access.csv
Labels: OE

#26063 [IMP] mrp: Added testcase for applying push rules on unbuild order.
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/mrp_byproduct/models/mrp_production.py
Labels: RD

#25354 11.0 mass mailing transcoder fix dep
  addons/web_editor/static/src/js/editor/transcoder.js
  odoo/tools/mail.py
Labels: RD

#26185 Master template v2 tde
  addons/mail/models/mail_activity.py
  addons/mail/static/src/js/activity.js
  addons/mail/static/src/scss/mail_activity.scss
  addons/mail/static/src/xml/activity.xml
  addons/mail/static/tests/chatter_tests.js
Labels: RD

#26191 [FIX] resource: don't lose minutes anymore
  addons/resource/models/resource.py
Labels: 11.0, OE

#25516 [FIX] google_calendar: rrule crash
  addons/calendar/models/calendar.py
Labels: OE

#25851 [FIX] sale: do not always overwrite discount on soline
  addons/sale/models/sale.py
Labels: OE

#26204 [FIX] base: show char field size in form view
  odoo/addons/base/ir/ir_model.py
Labels: OE

#26207 [FIX] point_of_sale: return with rounding < 0.01
  addons/point_of_sale/wizard/pos_payment.py
Labels: OE

#26033 [Fix]website: Fixed expected singleton
  addons/website/models/website.py
Labels: Website

#26216 [FIX] hr_holidays: Allocation Request not always in the Summary View
  addons/hr_holidays/report/hr_leave_report.py
Labels: OE

#26206 [FIX] stock, sale_stock: copy the to_refund field when splitting a move
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move.py
Labels: OE

#26219 [FIX] barcodes: ok PageUp/Down/Home/End in firefox
  addons/barcodes/static/src/js/barcode_events.js
Labels: OE

#26172 [FIX] account: regression - display partner_name as placeholder
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
Labels: Accounting

#26218 [FIX] account: default name for analytic line from aml
  addons/account/models/account_move.py
Labels: OE

#17040 [ADD] force tax included computation in reconcialiation widget
  addons/account/models/account.py
  addons/account/models/chart_template.py
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/src/xml/account_reconciliation.xml
  addons/account/views/account_view.xml
  addons/web/static/src/js/fields/abstract_field.js
  addons/web/static/src/js/fields/relational_fields.js
Labels: Accounting, RD

#26222 [FIX] payment_stripe: disable button
  addons/payment_stripe/static/src/js/stripe.js
Labels: OE

#26171 [FIX] pad_project: Avoid rewriting project on task saving
  addons/pad_project/models/project.py
Labels: Services

#26246 [FIX] stock: button_validate: forced move lines
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_picking.py
Labels: OE

#25970 Master website menus sed
  addons/website/models/res_config_settings.py
  addons/website/static/src/xml/website.backend.xml
  addons/website/views/res_config_settings_views.xml
  addons/website/views/website_navbar_templates.xml
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_views.xml
  addons/website_form/views/res_config_view.xml
  addons/website_forum/views/forum.xml
  addons/website_sale/models/res_config_settings.py
  addons/website_sale/static/src/xml/website_sale_dashboard.xml
  addons/website_sale/views/res_config_settings_views.xml
  addons/website_sale/views/sale_order_views.xml
  addons/website_slides/views/website_slides_backend.xml
Labels: RD

#26234 [FIX] mrp: remove mrp.message
  addons/mrp/models/__init__.py
  addons/mrp/models/mrp_message.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/security/ir.model.access.csv
  addons/mrp/views/mrp_workorder_views.xml
Labels: RD

#26249 Master datetime js adt
  addons/web/static/lib/py.js/lib/py_extras.js
  addons/web/static/tests/core/py_utils_tests.js
Labels: RD

#26245 [FIX] account: reconcile through widget associate payment/invoice
  addons/account/models/account_move.py
Labels: OE

#26243 [FIX] hr: Demo Data Fix
  addons/hr/data/hr_demo.xml
  addons/hr/static/img/employee_fp-image.jpg
Labels: RD

#26261 [FIX] sale: pass correct action when accessing quotation from email link
  addons/sale/models/sale.py
Labels: OE

#23831 Language Right to Left
  addons/account/static/src/scss/account_reconciliation.scss
  addons/delivery/views/delivery_view.xml
  addons/im_livechat/static/src/js/im_livechat.js
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/scss/abstract_thread_window.scss
  addons/mail/static/src/scss/systray.scss
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/views/point_of_sale.xml
  addons/portal/views/portal_templates.xml
  addons/web/static/src/js/chrome/abstract_web_client.js
  addons/web/static/src/js/core/dom.js
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/src/js/views/pivot/pivot_controller.js
  addons/web/static/src/scss/datepicker.scss
  addons/web/static/src/scss/dropdown.scss
  addons/web/static/src/scss/fontawesome_overriden.scss
  addons/web/static/src/scss/graph_view.scss
  addons/web/static/src/scss/report.scss
  addons/web/static/src/scss/search_view.scss
  addons/web/static/src/scss/ui.scss
  addons/web/static/src/scss/webclient.scss
  addons/web/static/src/scss/webclient_extra.scss
  addons/web/views/webclient_templates.xml
  addons/web_editor/views/iframe.xml
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/scss/tip.scss
  addons/website/static/src/scss/website.backend.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website_forum/views/website_forum.xml
  odoo/addons/base/data/res.lang.csv
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/test_assetsbundle/static/src/css/test_cssfile3.css
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
Labels: Localization, RD

#26051 Master sepa qr code sed
  addons/account/models/company.py
  addons/account/models/res_config_settings.py
  addons/account/views/report_invoice.xml
  addons/account/views/res_config_settings_views.xml
  addons/payment/views/payment_portal_templates.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: RD

#26318 [IMP] account, payment: relabeling and minor changes for payment acquirer step
  addons/account/views/account_onboarding_templates.xml
  addons/payment/models/res_company.py
  addons/payment/views/payment_acquirer_onboarding_templates.xml
  addons/payment/wizards/payment_acquirer_onboarding_wizard.py
  addons/sale/models/res_company.py
  addons/sale/views/sale_onboarding_views.xml
  addons/sale/wizard/payment_acquirer_onboarding_wizard.py
  odoo/addons/base/views/onboarding_views.xml
Labels: RD

#22699 [FIX] base: rename languages to be more international
  odoo/addons/base/res/res.lang.csv
Labels: RD

#24544 [FIX] tools: formatLang should use cached lang
  odoo/tools/misc.py
Labels: RD

#16141 [IMP] PoS: trust computed amounts
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/point_of_sale/wizard/__init__.py
  addons/point_of_sale/wizard/pos_discount.py
  addons/point_of_sale/wizard/pos_discount.xml
Labels: RD

#26317 [FIX] l10n_in: invoice col length kept same
  addons/l10n_in/views/report_invoice.xml
Labels: OE

#26181 [IMP] account: reconciliation widget: replace the pager with a `load …
  addons/account/models/reconciliation_widget.py
  addons/account/static/src/js/reconciliation/reconciliation_action.js
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/src/xml/account_reconciliation.xml
  addons/account/static/tests/reconciliation_tests.js
Labels: RD

#26107 [FIX] base: handle RedirectWarning exceptions during import
  odoo/exceptions.py
Labels: OE

#26316 [FIX] mass_mailing: bounced statistics
  addons/mass_mailing/models/mail_thread.py
  addons/mass_mailing/models/mass_mailing_stats.py
Labels: OE

#26302 [FIX] web: increase timeout
  addons/web/tests/test_js.py
Labels: RD

#26251 [IMP] account: change menus
  addons/account/report/account_invoice_report_view.xml
  addons/account/views/account_analytic_view.xml
  addons/account/views/account_invoice_view.xml
  addons/account/views/account_menuitem.xml
  addons/account/views/account_payment_view.xml
  addons/account/views/account_view.xml
  addons/account/views/tax_adjustments.xml
  addons/account_asset/views/account_asset_views.xml
  addons/account_asset/wizard/asset_depreciation_confirmation_wizard_views.xml
  addons/account_budget/views/account_budget_views.xml
  addons/account_voucher/views/account_voucher_views.xml
  addons/analytic/views/analytic_account_views.xml
Labels: RD

#26250 [IMP] account: hide impot button on bank statement
  addons/account/static/src/js/bank_statement.js
  addons/account/views/account.xml
Labels: RD

#26308 [FIX] sales_team: Fixed traceback while clicking on sales team menu
  addons/sales_team/models/crm_team.py
Labels: RD

#26301 [FIX] account: fiscal year last day
  addons/account/models/company.py
  addons/account/wizard/setup_wizards.py
Labels: OE

#26310 [FIX] stock: remove unnecessary manual step
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
Labels: OE

#25521 [FIX] l10n_in_stock: Fix xpath and change template variable move to ml in gst_report_picking_inherit.
  addons/l10n_in_stock/views/report_stockpicking_operations.xml
Labels: RD

#25819 Master event ticket name seb
  addons/event/views/event_views.xml
  addons/event_sale/models/event.py
  addons/event_sale/models/sale_order.py
  addons/event_sale/tests/test_event_sale.py
  addons/event_sale/views/event_views.xml
  addons/event_sale/views/sale_order_views.xml
  addons/product/models/product.py
  addons/sale/models/sale.py
  addons/sale_management/models/sale_order.py
  addons/website_event/models/event.py
  addons/website_event_sale/models/sale_order.py
  addons/website_event_sale/views/event_templates.xml
  addons/website_sale/models/sale_order.py
  addons/website_sale/views/templates.xml
Labels: RD

#25863 Improve the behaviour for import many2one and many2many fields
  addons/base_import/models/base_import.py
  addons/base_import/static/src/js/import_action.js
  addons/base_import/static/src/scss/base_import.scss
  addons/base_import/static/src/xml/base_import.xml
  odoo/addons/base/models/ir_fields.py
  odoo/addons/test_impex/models.py
  odoo/addons/test_impex/tests/test_load.py
  odoo/fields.py
Labels: RD

#25991 Master chrome headless devtools moc
  odoo/tests/common.py
  odoo/tests/phantomtest.js
Labels: RD

#26399 [FIX] purchase: rounding in supplier info
  addons/purchase/models/purchase.py
Labels: RD

#26303 [FIX] tools: sanitize allow white-space style
  odoo/tools/mail.py
Labels: OE

#26419 [FIX] calendar: date start
  addons/calendar/models/calendar.py
Labels: OE

#26411 [FIX] mail: schedule activity with user's today
  addons/hr_expense/models/hr_expense.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mail/models/ir_actions.py
  addons/mail/models/mail_activity.py
  addons/sale/models/sale.py
  addons/sale_purchase/models/purchase_order.py
  addons/sale_purchase/models/sale_order.py
Labels: RD, Services

#26432 [FIX] tests: clean the browser even on failure
  odoo/tests/common.py
Labels: RD

#26421 [FIX] stock: add origin to the chatter when creating a picking from a…
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move.py
Labels: OE

#26438 [FIX] sales_team: AccessError on default team
  addons/sales_team/models/crm_team.py
Labels: OE

#25210 10 odoo fix serialized field
  odoo/addons/base/ir/ir_model.py
  odoo/modules/registry.py
Labels: Framework

#26458 [REV] Revert "[FIX] Stock : deliveryslip report - prioritize partner_…
  addons/stock/report/report_deliveryslip.xml
Labels: RD

#25816 [FIX] purchase_requisition: Allow to change the vendor name on purcha…
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/views/purchase_requisition_views.xml
Labels: RD

#26418 [FIX] models: unlink `ir.property`
  odoo/addons/base/tests/test_orm.py
  odoo/models.py
Labels: OE

#26474 [FIX] crm: fix API
  addons/crm/models/crm_lead.py
Labels: OE

#25341 [FIX] account: Fix tax summary on invoice report
  addons/account/views/report_invoice.xml
Labels: 11.0, Accounting

#26488 [FIX] membership: cancel invoice
  addons/membership/models/account_invoice.py
  addons/membership/models/partner.py
Labels: OE

#26491 [FIX] sales_team: default team is active
  addons/sales_team/models/crm_team.py
Labels: OE

#26336 [FIX] account_voucher: copy product in acc voucher
  addons/account_voucher/models/account_voucher.py
Labels: Accounting

#18776 [IMP] maintenance:added effective date field in equipment & tools
  addons/maintenance/models/maintenance.py
  addons/maintenance/views/maintenance_views.xml
Labels: Logistics, RD

#26372 [FIX] delivery: fix view
  addons/delivery/views/delivery_view.xml
Labels: RD

#26518 [FIX] web: prevent textarea vertical resize on chrome
  addons/web/static/src/js/core/dom.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: RD

#19203 [ADD]stock_picking_batch: Add batch picking report by location.
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/data/stock_picking_batch_demo.xml
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/stock_picking_batch/report/stock_picking_batch_report_views.xml
Labels: Logistics, RD

#26512 [FIX] stock: compare quantities with different uom
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
Labels: RD

#26514 [FIX] mrp: restore produce produce test
  addons/mrp/tests/test_order.py
Labels: RD

#26407 [FIX] resource: allow to plan 0 hours
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
Labels: RD

#25945 [IMP] stock: Inventory Adjustment & Update quantity on hand improvement
  addons/stock/views/stock_inventory_views.xml
Labels: RD

#25923 [IMP] product: Add product uom and currency on product supplierinfo t…
  addons/product/models/product.py
  addons/product/views/product_views.xml
Labels: RD

#26499 [FIX] crm: make sure there is a create date when computing date_open
  addons/crm/models/crm_lead.py
Labels: OE

#26369 [FIX] sale_management: Traceback while sharing document to any recipients
  addons/sale_management/models/sale_order.py
Labels: RD

#26526 [FIX] mail: access token in received cid images
  addons/mail/models/mail_thread.py
Labels: OE

#25986 Master mrp bom variants mpa
  addons/mrp/models/mrp_bom.py
  addons/mrp/tests/test_bom.py
Labels: RD

#25062 [IMP] mrp: When modifying a BoM that is used in a MO not done, raise …
  addons/mrp/models/mrp_bom.py
  addons/mrp/tests/test_bom.py
  addons/mrp/tests/test_workorder_operation.py
Labels: RD

#26523 [FIX] account: allow range amount search for reconciliation widget
  addons/account/models/account_move.py
Labels: OE

#26435 [FIX] web: Don't allow keyboard shortcuts on BlockUI
  addons/web/static/src/js/chrome/keyboard_navigation_mixin.js
  addons/web/static/src/js/core/misc.js
Labels: RD

#26550 [FIX] project: fix sql injection in rating public controller
  addons/project/controllers/rating.py
Labels: RD, Security

#26106 [FIX] web: fix js data during consecutive sequence of resequence moves
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
Labels: OE

#26583 [FIX] account: unreconcile payment from invoice with exchange difference
  addons/account/models/account_move.py
Labels: OE

#26575 [FIX] tools:image: reset stream on crop
  odoo/tools/image.py
Labels: OE

#26516 [FIX] hr_holidays: officers can CRUD leaves for their companies
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/security/hr_holidays_security.xml
Labels: OE

#26608 [FIX][REF] mail: several thread windows fixes
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/xml/abstract_thread_window.xml
  addons/mail/static/tests/document_thread_window_tests.js
  addons/mail/static/tests/thread_window/basic_thread_window_tests.js
  addons/mail/static/tests/thread_window/blank_thread_window_tests.js
  addons/mail/static/tests/thread_window/hidden_thread_window_tests.js
  addons/mail/static/tests/thread_window_tests.js
  addons/mail/views/mail_templates.xml
Labels: Framework, RD

#26605 [FIX] stock_account: Display variant name in INVENTORY VALUATION report
  addons/stock_account/views/stock_account_views.xml
Labels: OE

#26287 [FIX] account: Rounding error with multi-currency payment
  addons/account/static/src/js/reconciliation/reconciliation_model.js
Labels: OE

#26636 [FIX] stock: move line: lot and product
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_robustness.py
Labels: RD

#26627 [FIX] web: restore access to minDate/maxDate functions on the DateWidget
  addons/web/static/src/js/widgets/date_picker.js
Labels: RD

#26645 [FIX] web: use an unused variable in mock server
  addons/web/static/tests/helpers/mock_server.js
Labels: OE

#26612 [IMP] mrp: Correct demo data for traceability report
  addons/mrp/data/mrp_demo.xml
Labels: RD

#26651 [FIX] mrp: 'To Consume' in workorder
  addons/mrp/views/mrp_workorder_views.xml
Labels: OE

#26634 [FIX] mail: right user_ids when calling /mail/follow
  addons/mail/controllers/main.py
Labels: OE

#25997 Feedback Sections on SO - SEB
  addons/account/controllers/portal.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/account/static/src/js/account_portal_sidebar.js
  addons/account/static/src/scss/section_and_note_backend.scss
  addons/account/views/account_invoice_view.xml
  addons/account/views/account_portal_templates.xml
  addons/account/views/account_report.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/views/account_portal_templates.xml
  addons/l10n_in/models/account_invoice.py
  addons/portal/controllers/portal.py
  addons/portal/models/portal_mixin.py
  addons/portal/views/portal_templates.xml
  addons/sale/controllers/portal.py
  addons/sale/data/sale_demo.xml
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/static/src/scss/sale_portal.scss
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/controllers/portal.py
  addons/sale_management/models/sale_order.py
  addons/sale_management/report/sale_report_templates.xml
  addons/sale_management/views/sale_portal_templates.xml
  addons/web/static/src/scss/layout_background.scss
  addons/web/static/src/scss/layout_boxed.scss
  addons/web/static/src/scss/list_view.scss
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: RD

#26646 [FIX] calendar: recurring events
  addons/calendar/models/calendar.py
Labels: OE

#26671 [FIX] hr_attendance: White screen if employee is not set
  addons/hr_attendance/static/src/js/my_attendances.js
Labels: OE

#26606 [FIX] website_sale: removed compute_currency function from qweb template in the t-esc with monetary widget
  addons/website_sale/views/templates.xml
Labels: RD

#26670 [FIX] purchase: keep vendor reference
  addons/purchase/models/account_invoice.py
Labels: OE

#26554 [FIX] base: remove error_context message from test log
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/base/tests/test_views.py
Labels: RD

#26546 [IMP] mail: improve discuss chatter envelop hover and fix glich.
  addons/mail/static/src/js/thread_widget.js
  addons/mail/static/src/scss/thread.scss
  addons/mail/static/src/xml/thread.xml
Labels: RD

#26684 [FIX] stock: avoid useless processing
  addons/stock/models/product.py
Labels: OE

#25929 [FIX] web: fix evaluation context of the domain selector
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/widgets/domain_selector.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: OE

#26653 [FIX] tests, web_tour: improve js error display in build details
  addons/web_tour/static/src/js/tour_manager.js
  odoo/tests/common.py
Labels: RD

#26609 [IMP] mrp, resource: usability improvements
  addons/mrp/models/mrp_routing.py
  addons/mrp/models/mrp_workcenter.py
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/views/mrp_workcenter_views.xml
  addons/mrp/views/mrp_workorder_views.xml
  addons/resource/views/resource_views.xml
Labels: RD

#26683 [FIX] sale: more explicit error message
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_analytic.py
Labels: OE

#26705 [FIX] base: user fields_get no add group if asked
  odoo/addons/base/res/res_users.py
Labels: OE

#26695 [FIX] mass_mailing_event: event domain
  addons/mass_mailing_event/models/event.py
Labels: OE
