Repository odoo/odoo, pull requests merged in 2018-05, with the labels that each got.

#24292 [FIX] web: checkbox in editable list are clickable
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/less/list_view.less
Labels: OE

#24445 [FIX] website_slides: avoid mixed content iframe when computing ifram…
  addons/website_slides/models/slides.py
Labels: OE

#24350 [FIX] web: inline views should share their fields
  addons/web/static/src/js/services/data_manager.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#24478 [FIX] product: variant in partner_ref
  addons/product/models/product.py
Labels: OE

#24515 Adding CLA
  doc/cla/individual/nomadic-coding.md
Labels: CLA

#24529 [FIX] stock_account: valuation value on out moves
  addons/stock_account/models/stock.py
Labels: OE

#24481 [IMP] base: Add a new module category 'Document Signatures'
  odoo/addons/base/data/ir_module_category_data.xml
Labels: RD

#24520 [FIX] gamification: support large amounts of goals in update_goals
  addons/gamification/models/goal.py
Labels: OE

#24525 [FIX] stock: Scheduled Date on transfers
  addons/stock/views/stock_picking_views.xml
Labels: OE

#24471 [FIX] web: don't change page before saving
  addons/web/static/src/js/views/list_view.js
  addons/web/static/src/js/views/list_view_editable.js
Labels: OE

#24533 [FIX] stock: symmetric reserve and unreserve
  addons/stock/models/stock_move.py
Labels: 11.0, OE

#22741 11.0 mail chat window bug fix abh
  addons/mail/static/src/js/chat_window.js
  addons/mail/static/src/js/composer.js
  addons/mail/static/src/js/document_viewer.js
  addons/mail/static/src/js/thread.js
  addons/mail/static/src/less/composer.less
  addons/mail/static/src/xml/thread.xml
  addons/mail/static/tests/chat_window_test.js
Labels: Framework, RD, Services

#24503 [IMP] Improve way to retrieve records to prefetch
  odoo/api.py
  odoo/models.py
Labels: RD

#24555 [FIX] stock: quant: reserve and unreserve on duplicated quants
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_move.py
Labels: 11.0, OE

#24569 [FIX] account_check_printing: multiple partners
  addons/account_check_printing/models/account_payment.py
Labels: OE

#24554 [FIX] mail: activity in date tz but counts are not
  addons/mail/models/mail_activity.py
  addons/mail/models/res_users.py
Labels: OE

#24568 [FIX] mrp: tracked by product with routing
  addons/mrp/models/mrp_workorder.py
Labels: OE

#24575 [FIX] account: default partner
  addons/account/views/partner_view.xml
Labels: OE

#21446 Warn when using "on_change" trigger with other action type than "code"
  addons/base_automation/models/base_automation.py
Labels: RD

#24146 [11.0][IMP] l10n_cr: l10n_cr_state_data.xml
  addons/l10n_cr/data/l10n_cr_state_data.xml
Labels: Localization

#24598 [FIX] mail tools: html_sanitize must keep useful styles from mass mailing
  odoo/tools/mail.py
Labels: OE

#24596 [FIX] stock: Quantity available according to the warehouse or location
  addons/stock/models/product.py
Labels: OE

#24531 [WIP][FIX] web_editor: drag and drop
  addons/web_editor/static/lib/summernote/src/js/EventHandler.js
  addons/web_editor/static/src/js/backend/fields.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
Labels: OE

#24617 [FIX] website_sale: fallback on payment term
  addons/website_sale/models/website.py
Labels: OE

#24556 [FIX] delivery: test robust to installed localization
  addons/delivery/tests/test_delivery_cost.py
Labels: OE

#24607 [FIX] website_event: typo tickets not disappear
  addons/website_event/static/src/js/website_event.js
Labels: OE

#24412 [IMP] mail: hide 'mark all read' buttton on mobile devices
  addons/mail/static/src/xml/discuss.xml
Labels: RD

#20351 Add "exclusive" binding type on actions (old client_action_relate)
  odoo/addons/base/ir/ir_actions.py
  odoo/models.py
  odoo/tools/convert.py
Labels: RD

#24621 [FIX] stock: incorrect PO sequence
  addons/stock/models/procurement.py
Labels: OE

#24653 [FIX] sale: All Channels Sales Orders
  addons/sale/report/report_all_channels_sales.py
Labels: OE

#24678 [FIX] sale_timesheet: set company currency
  addons/sale_timesheet/tests/test_timesheet_revenue.py
Labels: OE

#24677 [FIX] payment_adyen: bytes/str comparison
  addons/payment_adyen/models/payment.py
Labels: OE

#24642 [FIX] point_of_sale: user on invoice same as on order
  addons/point_of_sale/models/pos_order.py
Labels: OE

#24701 [FIX] website_sale: do not copy last SO
  addons/website_sale/models/res_partner.py
Labels: OE

#24650 [FIX] payment_sips: special characters
  addons/account_payment/models/payment.py
  addons/payment/models/payment_acquirer.py
  addons/payment_sips/models/payment.py
  addons/sale_payment/models/payment.py
Labels: OE

#24704 [FIX] project: sub-tasks
  addons/project/models/project.py
  addons/project/views/project_views.xml
Labels: OE

#24716 [FIX] purchase: move with zero qty
  addons/purchase/models/account_invoice.py
Labels: OE

#24706 [FIX] hr_recruitment: job stages choosen manually
  addons/hr_recruitment/views/hr_recruitment_views.xml
Labels: OE

#24176 [IMP] mail: prevent creation of activities to users that have no acce…
  addons/mail/models/mail_activity.py
  addons/test_mail/tests/test_mail_activity.py
Labels: RD

#24295 [FIX]note: chatter disply issue has been fixed
  addons/note/views/note_views.xml
Labels: RD

#24736 [FIX] account: tax computation at reconciliation$
  addons/account/static/src/js/reconciliation/reconciliation_model.js
Labels: OE

#24767 [FIX] mail: XHTML
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_gateway.py
Labels: OE

#24623 [IMP] server: intercept SIGXCPU and shutdown gracefully
  odoo/service/server.py
Labels: RD

#24553 product variants menu visible by variant group, no more in developer mode
  addons/mrp/views/product_views.xml
  addons/point_of_sale/views/product_view.xml
  addons/purchase/views/purchase_views.xml
  addons/sale/views/sale_views.xml
  addons/stock/views/product_views.xml
  addons/website_sale/views/sale_order_views.xml
Labels: RD

#24813 [IMP] mrp: add check for unproduced finished lots
  addons/mrp/models/mrp_production.py
Labels: OE

#24815 Saas 11.3 fix anglosaxon val oco
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/tests/test_anglo_saxon_valuation_reconciliation_common.py
Labels: RD

#24787 [FIX] stock: no loop in traceability report
  addons/stock/models/stock_traceability.py
  addons/stock/tests/test_move2.py
Labels: OE

#19443 [pos] Invoice options on pos configuration
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/res_company.py
  addons/point_of_sale/models/res_config_settings.py
  addons/point_of_sale/static/src/xml/pos.xml
  addons/point_of_sale/views/point_of_sale_dashboard.xml
  addons/point_of_sale/views/point_of_sale_view.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/point_of_sale/views/pos_order_view.xml
  addons/point_of_sale/views/product_view.xml
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_mercury/views/pos_config_setting_views.xml
Labels: Point of Sale, RD

#24809 [FIX] mrp: workorders of sub-BOMs
  addons/mrp/models/mrp_production.py
Labels: OE

#24847 [FIX] calendar: do not create events past year 9999
  addons/calendar/models/calendar.py
Labels: OE

#24608 [REF] base: assets: fallback on sassc if libsass not present
  odoo/addons/base/models/assetsbundle.py
Labels: RD

#24597 [IMP] various: Override _name_search,_search instead of name_search,s…
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/analytic/models/analytic_account.py
  addons/calendar/models/calendar.py
  addons/calendar/models/ir_attachment.py
  addons/calendar/models/mail_message.py
  addons/fleet/models/fleet_vehicle.py
  addons/maintenance/models/maintenance.py
  addons/point_of_sale/models/account_journal.py
  addons/product/models/product.py
  addons/product/models/product_attribute.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/purchase/models/purchase.py
  addons/sale/models/sale.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_picking.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_ui_menu.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/models/res_company.py
  odoo/addons/base/models/res_country.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_impex/models.py
Labels: RD

#24800 [FIX] website_sale_delivery: selection at first rendering
  addons/website_sale/static/src/js/website_sale_tour_buy.js
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: OE

#24885 [FIX] mass_mailing: unsubscribe not working in multi lang
  addons/mass_mailing/models/mail_mail.py
Labels: OE

#24790 Move XIDs management to end of export & batch further
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: RD

#24887 [FIX] stock: test not using downstream/upstream
  addons/stock/tests/test_move2.py
Labels: OE

#18570 [IMP] http: avoid saving sessions for auth='none' routes
  odoo/addons/base/controllers/rpc.py
  odoo/http.py
Labels: RD

#24900 [FIX] stock: Diplay return in tracability report
  addons/stock/models/stock_traceability.py
Labels: RD

#24604 Expense: EXP product
  addons/sale_expense/__manifest__.py
  addons/sale_expense/data/sale_expense_data.xml
  addons/sale_expense/data/sale_expense_demo.xml
  addons/sale_expense/views/product_view.xml
Labels: RD

#24682 [FIX] web: o2m editable decorated, paged, ordered supports adds/cancel
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#24914 [IMP] stock: set picking_type_id to readonly except in draft state
  addons/stock/models/stock_picking.py
Labels: OE

#24955 [FIX] payment: pre_msg
  addons/payment/views/payment_views.xml
Labels: OE

#24793 [FIX] hr_holidays: missing model renaming/split after a0f4f6548bdb9a26151fc8a292d152fc67d1a13c
  addons/hr_holidays/models/hr.py
Labels: RD

#24920 [FIX] base: missing rng attribute 'force_save' on fields
  odoo/addons/base/rng/common.rng
Labels: RD

#24962 [FIX] google_calendar: error type
  addons/google_calendar/models/google_calendar.py
Labels: OE

#24963 [FIX] account: partner read-only
  addons/account/views/account_view.xml
Labels: OE

#24965 [FIX] hw_escpos: complying to barcode method One
  addons/hw_escpos/escpos/escpos.py
Labels: OE

#24717 [REF] resource calendar
  addons/hr/models/hr.py
  addons/hr/views/hr_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_payroll/models/hr_payslip.py
  addons/mrp/models/mrp_workcenter.py
  addons/mrp/tests/test_oee.py
  addons/project/models/project.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/resource/models/resource.py
  addons/resource/models/resource_mixin.py
  addons/resource/tests/common.py
  addons/resource/tests/test_resource.py
  addons/resource/tests/test_resource_model.py
  addons/resource/views/resource_views.xml
Labels: RD
