Repository odoo/odoo, pull requests merged in 2018-03, with the labels that each got.

#23374 [FIX] event: location incorrectly set in mail template
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
Labels: OE

#23407 [FIX] account, account_asset, point_of_sale, stock_landed_costs: deci…
  addons/account/models/account_move.py
  addons/account_asset/models/account_asset.py
  addons/point_of_sale/models/pos_order.py
  addons/stock_landed_costs/models/stock_landed_cost.py
Labels: OE

#23409 [FIX] website_quote: view quote
  addons/website_quote/controllers/main.py
Labels: OE

#23413 [FIX] website_crm_partner_assign: modify lead
  addons/website_crm_partner_assign/models/crm_lead.py
Labels: OE

#22793 [IMP] account: Remove frenglish
  addons/account/models/account.py
Labels: Internationalization

#23424 [FIX] l10n_in: display taxes with correct rounding
  addons/l10n_in/views/report_invoice.xml
Labels: OE

#22875 [FIX] stock: cancel a move line in planned transfer
  addons/stock/models/stock_picking.py
Labels: RD

#22962 [FIX] stock: merge move with a mix RFQ/PO
  addons/purchase/models/stock.py
  addons/purchase/tests/test_create_picking.py
Labels: RD

#23423 [FIX] stock: avoid block of schedulers
  addons/stock/models/procurement.py
Labels: OE

#23283 [FIX] payment: Unable to pay if character '/' in reference
  addons/payment/controllers/portal.py
  addons/payment/views/payment_portal_templates.xml
  addons/payment_stripe/static/src/js/stripe.js
Labels: RD

#23426 [FIX] pad, pad_project, note_pad: duplicate object
  addons/note_pad/models/note.py
  addons/pad/models/pad.py
  addons/pad_project/models/project.py
Labels: OE

#23350 [FIX] mail: activities of archived records
  addons/mail/models/mail_activity.py
Labels: Blocked, OE

#23469 [FIX] web: show error when trying to export a report with more than 2…
  addons/web/static/src/js/views/pivot_view.js
Labels: OE

#23392 [FIX] website_sale: update when changing quantity
  addons/website_sale/controllers/main.py
  addons/website_sale/data/demo.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_sale_options/static/src/js/website_sale.test.js
  addons/website_sale_options/views/website_sale_options_templates.xml
  addons/website_sale_stock/static/src/js/website_sale_stock.js
Labels: OE

#23467 [FIX] website_sale: update when changing quantity
  addons/website_sale/controllers/main.py
  addons/website_sale/data/demo.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_sale_options/static/src/js/website_sale.test.js
  addons/website_sale_options/views/website_sale_options_templates.xml
  addons/website_sale_stock/static/src/js/website_sale_stock.js
Labels: OE

#23110 Saas 11.2 account fix analytic accounting jao
  addons/account_analytic_default/models/sale_order_line.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/views/purchase_requisition_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
Labels: RD

#23415 [FIX] web: Impossible to delete a line in a tree view
  addons/web/static/src/xml/base.xml
Labels: OE

#23331 [FIX] stock_account, sale_stock, stock_dropshipping: dropshipping valuation
  addons/sale_stock/models/account_invoice.py
  addons/stock_account/models/stock.py
  addons/stock_dropshipping/tests/__init__.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
Labels: OE

#23471 [FIX] website_form: public user can send attachment
  addons/website_form/controllers/main.py
Labels: OE

#23490 [FIX] im_livechat: empty regex
  addons/im_livechat/models/im_livechat_channel.py
Labels: OE

#22831 [IMP] web: while hovering over link cursor style stays same when there is no content to show.
  addons/web/static/src/less/views.less
Labels: RD

#23477 [REF] stock, purchase: scheduler move exception
  addons/purchase/models/purchase.py
  addons/stock/models/procurement.py
Labels: RD

#23265 [FIX] barcode: set quantity with key press
  addons/barcodes/static/src/js/barcode_form_view.js
Labels: RD

#23497 [FIX] stock: fix various bug in picking views
  addons/stock/data/stock_demo.yml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/views/stock_picking_views.xml
Labels: RD

#23517 [FIX] l10n_be_hr_payroll_fleet: max cars
  addons/l10n_be_hr_payroll_fleet/views/res_config_settings_views.xml
Labels: OE

#23256 [FIX] barcodes: Do not trigger useless onchange server side.
  addons/barcodes/static/src/js/barcode_form_view.js
Labels: OE

#23525 [FIX] point_of_sale: return product
  addons/point_of_sale/models/pos_order.py
Labels: OE

#23519 [FIX] website_sale: display public user pricelist on the shop
  addons/website_sale/models/website.py
Labels: OE

#23535 [FIX] purchase, stock_dropshipping: fix tests
  addons/purchase/test/fifo_price.yml
  addons/stock_dropshipping/test/lifo_price.yml
Labels: RD

#23540 [FIX] purchase: Changing the price of a confirmed PO before the receipt
  addons/purchase/models/stock.py
Labels: OE

#23544 [FIX] portal: no note in frontend chatter w/ token
  addons/portal/controllers/mail.py
Labels: OE

#23546 [FIX] point_of_sale: round unit_price
  addons/point_of_sale/static/src/js/models.js
Labels: OE

#23547 [FIX] stock: "Picking Moves" on quant
  addons/stock/models/stock_quant.py
Labels: OE

#23563 [FIX] account: tax rounding
  addons/account/views/account_invoice_view.xml
Labels: OE

#23488 [IMP] fields: Allow shared fields
  odoo/addons/base/models/ir_model.py
  odoo/fields.py
Labels: Framework, RD

#23518 [FIX] l10n_ch: config and css ISR scanline offset
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/models/res_company.py
  addons/l10n_ch/models/res_config_settings.py
  addons/l10n_ch/report/isr_report.xml
  addons/l10n_ch/static/src/less/report_isr.less
  addons/l10n_ch/views/res_config_settings_views.xml
Labels: OE

#23567 [FIX] l10n_fr_fec: escape references
  addons/l10n_fr_fec/wizard/account_fr_fec.py
Labels: OE

#23587 [FIX] website: edit company data
  addons/website/static/src/js/editor/snippets.options.js
Labels: OE

#23494 [FIX] fields: empty date or datetime
  odoo/fields.py
Labels: OE

#23595 [FIX] website_crm: contactus_thanks
  addons/website_crm/i18n/website_crm.pot
Labels: OE

#23593 [FIX] portal: no dynamic chatter on edit so no dup
  addons/portal/static/src/js/portal_chatter.js
Labels: OE

#23602 CLA dajmi5
  doc/cla/corporate/dajmi5.md
Labels: CLA

#23604 [FIX] website_sale: 40px for mobile/list view/desc
  addons/website_sale/static/src/css/website_sale.css
  addons/website_sale/static/src/css/website_sale.sass
Labels: OE

#23551 [FIX] registry, loading: re-init inherited SQL views
  addons/sale/__init__.py
  addons/sale_margin/__init__.py
  addons/sale_margin/__manifest__.py
  odoo/modules/loading.py
  odoo/modules/registry.py
Labels: RD

#23611 [FIX] website_event_sale: pricelist show no discount
  addons/website_event_sale/views/event_templates.xml
Labels: OE

#23542 [FIX] account: tax rounding
  addons/account/models/account_invoice.py
Labels: OE

#23537 [FIX] website_sale: display prices using public user pricelist on the…
  addons/website_sale/models/sale_order.py
Labels: OE

#23606 CLA dajmi5 branch 10.0
  doc/cla/corporate/dajmi5.md
Labels: CLA

#23613 [FIX] payment, payment_authorize: company field in authorize.net
  addons/payment/models/payment_acquirer.py
  addons/payment_authorize/views/payment_authorize_templates.xml
Labels: OE

#23614 [FIX] portal: no dynamic chatter on edit so no dup
  addons/portal/static/src/js/portal_chatter.js
  addons/portal/views/portal_templates.xml
Labels: OE

#23258 [REF] *: put `clickable` in widget options for statusbar
  addons/crm/views/crm_lead_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/gamification/views/challenge.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mass_mailing/views/mass_mailing_views.xml
  addons/note/views/note_views.xml
  addons/payment/views/payment_views.xml
  addons/project/views/project_views.xml
  addons/survey/views/survey_views.xml
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/website_event_track/views/event_track_views.xml
Labels: RD

#21750 [IMP] web_tour: specify timeout per step
  addons/web_tour/static/src/js/tour_manager.js
Labels: Framework

#23640 [FIX] website_sale: image in carousel
  addons/website_sale/views/templates.xml
Labels: OE

#23663 [ADD] l10n_nl: add Dutch states
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/res.country.state.csv
Labels: Localization

#23642 [FIX] crm: create opportunity from kanban
  addons/crm/views/crm_lead_views.xml
Labels: OE

#23653 [FIX] calendar: in multicompany user cannot access own calendar
  addons/calendar/models/calendar.py
Labels: OE

#23655 [FIX] account: false complete_tax_set tax default
  addons/account/models/chart_template.py
Labels: OE

#23673 [FIX] stock: picking in mobile view
  addons/stock/views/stock_move_views.xml
Labels: OE

#23676 [FIX] crm: favorite filters
  addons/crm/report/crm_opportunity_report_views.xml
Labels: OE

#23260 Allow multiple transport mode
  addons/l10n_be_hr_payroll/views/l10n_be_hr_payroll_view.xml
  addons/l10n_be_hr_payroll_fleet/views/hr_contract_views.xml
Labels: RD

#23682 [FIX] web_editor: modal fullscreen is fullscreen
  addons/web_editor/static/src/less/web_editor.backend.less
Labels: OE

#23583 [FIX] payment: do not refund transactions if they need 3DS validation
  addons/payment/models/payment_acquirer.py
Labels: 11.0, RD

#21868 [IMP] mail : composer / chatter new followers email address tooltips.
  addons/mail/static/src/js/many2many_tags_email.js
  addons/mail/static/src/xml/composer.xml
  addons/mail/static/tests/chatter_tests.js
Labels: RD

#23688 [FIX] website: make 'Optimize SEO' working again (for empty fields)
  addons/website/views/website_templates.xml
Labels: RD

#23622 [REM] crm, project: remove support of mail-based record update
  addons/crm/models/crm_lead.py
  addons/project/models/project.py
  odoo/tools/mail.py
Labels: RD

#23603 [FIX] stock: create new quality checks to pass for backorders
  addons/purchase/models/stock.py
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
Labels: OE

#19563 [Fix] warehouse name in multicompany env
  addons/stock/data/stock_data.xml
  addons/stock/models/stock_warehouse.py
Labels: Logistics

#23700 [FIX] web_editor: type of `res_id`
  addons/web_editor/controllers/main.py
Labels: OE

#23706 [FIX] portal: show line return in chatter message
  addons/portal/controllers/mail.py
Labels: OE

#23710 [FIX] hr_timesheet: change department
  addons/hr_timesheet/hr_timesheet.py
Labels: OE

#23681 [FIX]account: Accounting reconciliation problem
  addons/account/models/account_move.py
Labels: OE

#23731 Create odoo_house.md
  doc/cla/corporate/odoo_house.md
Labels: CLA

#23715 [CLA] create mpanarin.md
  doc/cla/individual/mpanarin.md
Labels: CLA

#23008 [FIX] payment_adyen: fix error while making payment with adyen
  addons/payment_adyen/models/payment.py
Labels: RD

#23714 [ADD] l10n_be: add states for Belgium
  addons/l10n_be/__manifest__.py
  addons/l10n_be/data/res.country.state.csv
Labels: Localization

#23739 [FIX] JPY rounding
  odoo/addons/base/res/res_currency_data.xml
Labels: 10.0, Localization

#22612 [IMP] http: Sessions implicit deactivation
  addons/auth_crypt/models/res_users.py
  addons/auth_oauth/models/res_users.py
  odoo/addons/base/res/res_users.py
  odoo/http.py
  odoo/service/security.py
  odoo/tests/common.py
Labels: RD

#23737 [FIX] website_sale: required fields
  addons/website_sale/views/templates.xml
Labels: OE

#23759 [FIX] website_project{_issue}: redirect from email
  addons/website_project/models/project.py
  addons/website_project_issue/models/project_issue.py
Labels: OE

#23761 [FIX] product: default quantityon pricelist item
  addons/product/pricelist.py
Labels: OE

#23744 [FIX] mass_mailing: domain translation
  addons/mass_mailing/models/mass_mailing.py
Labels: OE

#23693 [FIX] sale: Wrong display of taxes in PRO-FORMA
  addons/sale/models/sale.py
Labels: OE

#23747 [FIX] mass_mailing: domain translation
  addons/mass_mailing/models/mass_mailing.py
Labels: OE

#23743 [FIX] l10n_ch: ignore stylistic background
  addons/l10n_ch/static/src/less/report_isr.less
Labels: OE

#22746 [IMP] sale_payment: set invoice id in transaction form after successf…
  addons/account_payment/models/payment.py
  addons/payment/models/payment_acquirer.py
  addons/sale_payment/models/payment.py
Labels: RD, Services

#23766 [FIX] account: unreconcile payment
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
Labels: OE

#23778 [FIX] stock_account: Cannot validate a Customer Credit
  addons/stock_account/models/account_invoice.py
Labels: OE

#22960 [IMP] hr: remove record.ids from condition at check alias contact
  addons/hr/models/mail_alias.py
Labels: RD

#23788 [FIX] crm: create opportunity from kanban
  addons/crm/views/crm_lead_views.xml
Labels: OE

#23774 [FIX] stock: Delivery Slip
  addons/stock/report/report_deliveryslip.xml
Labels: OE

#21116 [FIX] base: gives traceback while exporting more than one reports its…
  odoo/addons/base/ir/ir_actions.py
Labels: Framework, RD

#23798 [FIX] base_import: import empty date/datetime
  addons/base_import/models/base_import.py
Labels: OE

#23819 [FIX] mail: strip comments when inlining
  addons/mail/static/src/js/utils.js
Labels: OE

#23799 [FIX] web: Modify existing sales order lines
  addons/web/static/src/js/views/form_relational_widgets.js
Labels: OE

#23809 [FIX] web: don't loose focus when editing cell in list
  addons/web/static/src/js/views/basic/basic_renderer.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#23824 [FIX] stock_account: compute price if no product
  addons/stock_account/models/product.py
Labels: OE

#23020 [IMP] stock: traceability button not shown when tracking is none
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_picking_views.xml
Labels: Logistics, RD

#23635 11.0 rounding issue kme
  addons/stock/models/stock_traceability.py
Labels: Logistics, RD

#23846 [FIX] stock: date field on move line after `_action_done`
  addons/stock/models/stock_move_line.py
Labels: RD

#23856 [FIX] web: incorrect date in calendar
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: OE

#23857 [FIX] purchase: hide PO when not necessary
  addons/purchase/views/account_invoice_views.xml
Labels: OE

#23847 [FIX] website: see versionning changes
  addons/website/models/ir_http.py
  addons/website/models/website.py
Labels: OE

#23872 [FIX] ir_model: Cascade delete custom o2m and related fields
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: RD

#23873 [FIX] mrp: date expected
  addons/mrp/models/mrp_production.py
Labels: OE

#23881 [FIX] sale_timesheet: 100 % discount SO line
  addons/sale_timesheet/models/account_invoice.py
Labels: OE

#23897 [FIX] payment_authorize: raise error is incomplete information
  addons/payment_authorize/models/authorize_request.py
Labels: OE

#23899 [FIX] payment_authorize: ZIP code is optional
  addons/payment_authorize/models/authorize_request.py
Labels: OE

#23884 [FIX] stock: stock.move.line: `_free_reservation`
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: RD

#23903 [FIX] account, base: default partner
  addons/account_bank_statement_import/account_bank_statement_import.py
Labels: OE

#23773 [FIX] stock: allow to validate a picking with 2 extra moves
  addons/mrp/models/stock_move.py
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move2.py
Labels: OE

#23907 [FIX] account: Name of an account.payment
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
Labels: OE

#23896 [FIX] web: correctly display reference field in subview
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#23839 [FIX] stock_account: Wrong decorator
  addons/stock_account/stock_account.py
Labels: RD

#23905 [FIX] web_editor: block only the form's buttons
  addons/web_editor/static/src/js/backend.js
Labels: RD

#23882 [FIX] account: fix performance issue with check_lock_date
  addons/account/models/account_move.py
Labels: Accounting, Performance

#23858 [FIX] base: khmer language (Cambodia)
  odoo/addons/base/base_data.xml
  odoo/addons/base/res/res.lang.csv
Labels: RD

#23923 [FIX] calendar: set color on right partner
  addons/calendar/models/calendar.py
Labels: OE

#23915 [FIX] account: reverse pair
  addons/account/models/account_move.py
Labels: OE

#23932 [FIX] website_sale_delivery: repr of floats
  addons/website_sale_delivery/controllers/main.py
Labels: OE

#23940 [FIX] stock_landed_costs: digits precision
  addons/stock_landed_costs/models/stock_landed_cost.py
Labels: OE

#23943 [FIX] doc: report with xmlrpc
  doc/webservices/odoo.rst
Labels: OE

#23956 [FIX] stock: settinge don't enable disabled wh op
  addons/stock/models/res_config_settings.py
Labels: OE
