Repository odoo/odoo, pull requests merged in 2018-04, with the labels that each got.

#23964 [FIX] analytic, hr_timesheet: recompute order
  addons/analytic/models/analytic_account.py
  addons/hr_timesheet/models/hr_timesheet.py
Labels: RD

#23997 [FIX] account: invoice line form ok studio context
  addons/account/views/account_invoice_view.xml
Labels: OE

#24000 [FIX] account: fix test
  addons/account/models/account_analytic_line.py
Labels: OE

#23651 [FIX] account_payment: Use invoice's access token
  addons/account_payment/controllers/payment.py
Labels: RD

#23620 [ADD] test showing an ORM problem
  odoo/addons/test_testing_utilities/ir.model.access.csv
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/models.py
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
Labels: RD

#24010 [FIX] calendar: comparing timezoned datetimes
  addons/calendar/models/calendar.py
Labels: OE

#24004 [FIX] base: `user.share` recomputation
  odoo/addons/base/res/res_config.py
Labels: OE

#23969 [FIX] mail_activity: state of activirty is TZ dependent
  addons/mail/models/mail_activity.py
Labels: OE

#24015 [FIX] sale_timesheet: undefined variable
  addons/sale_timesheet/models/account_invoice.py
Labels: OE

#24027 [FIX] product_email_template: use regular HTML widget
  addons/product_email_template/views/mail_template_views.xml
Labels: OE

#23967 [CLA] Add RobinetDenisAcsone into Acsone CLA
  doc/cla/corporate/acsone.md
Labels: CLA

#24029 [FIX] calendar: fix event sorting function
  addons/calendar/models/calendar.py
Labels: OE

#22798 Modernize TGZ translations export
  odoo/addons/base/wizard/base_export_language_views.xml
  odoo/tools/translate.py
Labels: RD

#24011 [FIX] purchase & stock_dropshipping: fix some tests
  addons/purchase/test/fifo_price.yml
  addons/stock_dropshipping/test/lifo_price.yml
Labels: Accounting

#24042 [FIX] theme_*: restore category to theme
  addons/theme_bootswatch/__openerp__.py
  addons/theme_default/__openerp__.py
Labels: OE

#24036 [FIX] web: loss of context when duplicating
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/views/form_tests.js
Labels: OE

#22493 Batch generation of XIDs
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: RD

#24045 [FIX] http: Bokmål language code
  odoo/http.py
Labels: OE

#23860 [FIX] sale_stock: To avoid singleton error
  addons/sale_stock/models/sale_order.py
Labels: Logistics

#24062 Master normalize domain ops adt
  odoo/addons/base/tests/test_expression.py
  odoo/osv/expression.py
Labels: Framework, RD

#24076 [FIX] account: missing decorator
  addons/account/models/account_invoice.py
Labels: RD

#24098 [FIX] stock: location barcode more than one page
  addons/stock/report/report_location_barcode.xml
Labels: OE

#24077 [FIX] web: check domain after action button in kanban
  addons/web/static/src/js/views/kanban/kanban_controller.js
  addons/web/static/tests/views/kanban_tests.js
Labels: OE

#24128 [FIX] note: css margins of next activity
  addons/note/views/note_views.xml
Labels: OE

#24130 [FIX] account_asset: Access error with shared product with deferred revenue
  addons/account_asset/account_asset_invoice.py
Labels: OE

#23689 [IMP] im_livechat, mail: replace emoji with unicode.
  addons/im_livechat/__manifest__.py
  addons/im_livechat/data/im_livechat_channel_data.xml
  addons/im_livechat/data/mail_shortcode_demo.xml
  addons/im_livechat/static/src/js/im_livechat.js
  addons/im_livechat/views/im_livechat_channel_views.xml
  addons/mail/__manifest__.py
  addons/mail/controllers/main.py
  addons/mail/data/mail_shortcode_data.xml
  addons/mail/models/mail_shortcode.py
  addons/mail/static/src/img/smiley/angry.png
  addons/mail/static/src/img/smiley/beer.png
  addons/mail/static/src/img/smiley/bug.png
  addons/mail/static/src/img/smiley/cake.png
  addons/mail/static/src/img/smiley/cat.png
  addons/mail/static/src/img/smiley/coffee.png
  addons/mail/static/src/img/smiley/confused.png
  addons/mail/static/src/img/smiley/cookie.png
  addons/mail/static/src/img/smiley/evil.png
  addons/mail/static/src/img/smiley/flushed.png
  addons/mail/static/src/img/smiley/ghost.png
  addons/mail/static/src/img/smiley/heart.png
  addons/mail/static/src/img/smiley/laugh.png
  addons/mail/static/src/img/smiley/monkey_eye.png
  addons/mail/static/src/img/smiley/monkey_hear.png
  addons/mail/static/src/img/smiley/monkey_speak.png
  addons/mail/static/src/img/smiley/neutral.png
  addons/mail/static/src/img/smiley/normal_smile.png
  addons/mail/static/src/img/smiley/open_mouth.png
  addons/mail/static/src/img/smiley/party.png
  addons/mail/static/src/img/smiley/poop.png
  addons/mail/static/src/img/smiley/sad.png
  addons/mail/static/src/img/smiley/scream.png
  addons/mail/static/src/img/smiley/smile.png
  addons/mail/static/src/img/smiley/smile_open_mouth.png
  addons/mail/static/src/img/smiley/stuck_out_tongue.png
  addons/mail/static/src/img/smiley/sunglass.png
  addons/mail/static/src/img/smiley/tears_of_joy.png
  addons/mail/static/src/img/smiley/thumbsdown.png
  addons/mail/static/src/img/smiley/thumbsup.png
  addons/mail/static/src/img/smiley/trollface.png
  addons/mail/static/src/img/smiley/trophy.png
  addons/mail/static/src/img/smiley/wink.png
  addons/mail/static/src/img/smiley/yum.png
  addons/mail/static/src/js/services/chat_manager.js
  addons/mail/static/src/less/composer.less
  addons/mail/static/src/xml/composer.xml
  addons/rating/models/rating.py
  addons/rating/static/src/img/rating_0.png
  addons/rating/static/src/img/rating_1.png
  addons/rating/static/src/img/rating_10.png
  addons/rating/static/src/img/rating_5.png
Labels: RD

#24139 [FIX] point_of_sale: POS anglo-saxon in FIFO
  addons/point_of_sale/models/pos_order.py
Labels: OE

#24064 [FIX] stock_landed_costs: defer AML creation
  addons/stock_landed_costs/models/stock_landed_cost.py
Labels: OE

#24153 [FIX] stock_calendar: scheduled data
  addons/stock_calendar/models/stock.py
Labels: OE

#24137 [FIX] mail: composer expand
  addons/mail/static/src/less/composer.less
Labels: OE

#23883 [FIX] mass_mailing: Allow multiple recipients in mailing.
  addons/mass_mailing/models/mass_mailing.py
Labels: RD, Services

#24155 [FIX] payment_authorize: number of decimals
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
Labels: OE

#24144 [Imp]google_calendar: Added context in action
  addons/google_calendar/views/res_config_settings_views.xml
Labels: 11.0, Services

#24157 [FIX] mrp_repair: repair fee lines without product_id filled
  addons/mrp_repair/views/mrp_repair_views.xml
Labels: OE

#24171 [FIX] pos_mercury: allow test transactions again
  addons/pos_mercury/data/pos_mercury_demo.xml
  addons/pos_mercury/models/pos_mercury_transaction.py
Labels: 9.0, OE, Point of Sale

#24161 [FIX] base: amount_to_text possible difference
  odoo/addons/base/res/res_currency.py
  odoo/addons/base/tests/test_float.py
Labels: OE

#24165 [FIX] account: Warn users if group taxes have recurrency,
  addons/account/models/account.py
Labels: OE

#24180 [FIX] purchase: Procurement rule Buy missing when installing Purchase
  addons/purchase/data/purchase_stock_demo.yml
Labels: OE

#24162 [FIX] purchase : be able to use it with MPS
  addons/purchase/models/purchase.py
Labels: RD

#24192 [FIX] pos_mercury: don't lose credit card info
  addons/pos_mercury/models/pos_mercury.py
Labels: 10.0, OE, Point of Sale

#24175 [FIX] website_project: add website_url field to project.project
  addons/website_project/models/project.py
Labels: OE

#24138 [FIX] stock_account: display to_refund on return picking as toggle
  addons/stock_account/views/stock_account_views.xml
Labels: OE

#24182 [FIX] web_editor: indent just a line inside table
  addons/web_editor/static/src/js/summernote.js
Labels: OE

#24177 [FIX] base_import: checkbox relational fields
  addons/base_import/models/base_import.py
  addons/base_import/static/src/js/import_action.js
  addons/base_import/static/src/xml/base_import.xml
  addons/base_import/tests/test_base_import.py
Labels: OE

#24201 [FIX] stock: location barcode no all page on one
  addons/stock/report/report_location_barcode.xml
Labels: OE

#24213 [FIX] hr_timesheet: description on timesheet report
  addons/hr_timesheet/report/report_timesheet_templates.xml
Labels: OE

#24097 [WIP] web: o2m list with field from server
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#23958 [IMP] doc: add profiler example
  doc/howtos/profilecode.rst
Labels: RD

#24223 [FIX] web: remove &shy; when saving phone number
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: OE

#23920 [FIX] project: subtasks should be taken into account even if archived
  addons/project/models/project.py
Labels: OE

#24221 [FIX] account: default taxes
  addons/account/models/res_config.py
Labels: OE

#23633 [FIX]sale: Set correct income account in invoice if income account is…
  addons/sale/wizard/sale_make_invoice_advance.py
Labels: Accounting, RD

#24188 [FIX] web: setDate mixing utc+tz and local date
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: OE

#23842 [FIX] purchase: in purchase.order.line, "product_type" related field …
  addons/purchase/models/purchase.py
Labels: RD

#24259 [FIX] payment: Portal payment were not saving tokens
  addons/payment/controllers/portal.py
Labels: RD

#24264 [CLA] Update Vauxoo's CLA
  doc/cla/corporate/vauxoo.md
Labels: CLA

#23188 [FIX] web_editor,mail: send email's attachments without write access
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/fields.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
Labels: RD

#24270 [FIX] stock: company on Procurement Rules
  addons/stock/views/procurement_views.xml
  addons/stock/views/stock_location_views.xml
Labels: OE

#24258 [FIX]mrp: Byproducts are produced twice
  addons/mrp/models/mrp_workorder.py
Labels: OE

#24215 [FIX] web: pivot: correctly save and restore groupbys on rows and cols
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
Labels: OE

#24263 [FIX] pad: prevent concat bool and string
  addons/pad/models/pad.py
Labels: OE

#24219 11.0 fix barcode various arm
  addons/barcodes/static/src/js/barcode_form_view.js
  addons/barcodes/static/tests/barcode_tests.js
Labels: RD

#24257 [FIX] models: bad setup of inherited custom fields
  odoo/fields.py
  odoo/models.py
Labels: OE

#24313 [FIX] account: missing widget
  addons/account/views/account_view.xml
Labels: OE

#24291 [FIX] mail: auto-subscribe at user creation
  addons/mail/models/res_users.py
Labels: OE

#24337 [FIX] mrp: change BOM
  addons/mrp/models/mrp_production.py
Labels: OE

#24242 [REF] stock: _action_assign
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
Labels: OE

#24346 [Fix] mail: cover more cases for URLs
  addons/mail/static/src/js/utils.js
  addons/mail/static/tests/mail_utils_tests.js
Labels: RD

#24309 [FIX] stock: update qty_done in move wizard
  addons/stock/models/stock_move.py
Labels: RD

#20463 [FIX] web: calendar sidebar filters not show only checkbox if filter …
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: Framework, RD

#24307 [FIX] web: NFD UTF-8 for safari in upload file
  addons/web/controllers/main.py
Labels: OE

#24304 [FIX] account, purchase, sale: Wrong company displayed in the footer
  addons/account/data/email_template_data_invoice.xml
  addons/purchase/data/mail_template_data.xml
  addons/sale/data/mail_template_data.xml
Labels: OE

#24351 [FIX] base_import_module: imported module version
  addons/base_import_module/models/ir_module.py
Labels: OE

#24348 [FIX] account: print invoice
  addons/account/models/account_invoice.py
  addons/account/views/account_report.xml
Labels: OE

#24368 [FIX] mrp: Wrong decimal format in user error
  addons/mrp/i18n/mrp.pot
  addons/mrp/wizard/change_production_qty.py
Labels: OE

#24300 [FIX] website_blog: wrong parse background-image generate console error
  addons/website_blog/static/src/js/website_blog.editor.js
Labels: RD

#24344 [FIX] purchase: use PO company for PO notification
  addons/purchase/data/mail_template_data.xml
  addons/purchase/i18n/purchase.pot
Labels: OE

#24369 [FIX] account_check_writing: write multi payment
  addons/account_check_printing/models/account_payment.py
Labels: OE

#24371 11.0 fix css massmailing chm
  addons/web_editor/static/src/js/editor/transcoder.js
Labels: RD

#24315 [FIX] mrp: dynamic bom report correct bom cost
  addons/mrp/report/mrp_report_bom_structure.py
Labels: RD

#24396 [FIX] web: pivot race condition load data
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
Labels: OE

#23616 [kanban] Archive all CTA + warning popup
  addons/web/static/src/js/views/kanban/kanban_column.js
  addons/web/static/src/js/views/kanban/kanban_controller.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/xml/kanban.xml
  addons/web/static/tests/views/kanban_tests.js
  addons/web/static/tests/views/list_tests.js
Labels: Framework, RD

#24407 [FIX] account: reconciliation model with Tax 0
  addons/account/static/src/js/reconciliation/reconciliation_model.js
Labels: OE

#24409 [FIX] delivery: fix test
  addons/delivery/tests/test_delivery_cost.py
Labels: OE

#24410 [FIX] stock: picking: do_unreserve
  addons/stock/models/stock_move.py
Labels: OE

#24392 [FIX] account: unreconcile payment
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
Labels: OE

#24439 [FIX] account: unreconcile payment
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
Labels: RD

#24434 [P3] [FIX] web: Explicitly decode the JS files in tests.
  addons/web/tests/test_js.py
Labels: 11.0, Framework

#22903 [Project] Improve padding when cover image
  addons/web/static/src/scss/kanban_view.scss
Labels: RD, Services

#24418 [FIX] mail: onchange activity
  addons/mail/models/mail_activity.py
Labels: OE

#24433 [FIX] product: name search `not ilike`
  addons/product/models/product.py
  addons/product/tests/test_variants.py
Labels: OE

#24442 [FIX] web: `get_file` and CPU time exceeded
  addons/web/static/src/js/framework/ajax.js
Labels: OE

#24444 [FIX] payment: Error to get the default country for a partner
  addons/payment/models/payment_acquirer.py
Labels: OE

#24424 [FIX] web_editor: firefox remember CTRL+A selection
  addons/web_editor/static/src/js/rte.summernote.js
Labels: OE

#24449 [FIX] mail: emoji substitution
  addons/mail/static/src/js/chat_manager.js
Labels: OE

#24446 [FIX] sql_db: log-level debug_sql log parameters
  odoo/sql_db.py
Labels: OE

#24387 [FIX] stock: allow inventory user to validate delivery orders when mo…
  addons/stock/models/stock_move.py
Labels: OE

#24386 [FIX] stock: allow inventory user to validate delivery orders when ac…
  addons/account/models/account_move.py
  addons/stock_account/models/stock.py
Labels: OE

#24476 [FIX] account_check_printing: multi payment has amount in words
  addons/account_check_printing/models/account_payment.py
Labels: OE

#24480 [FIX] stock_account: fifo, anglosaxon and return
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_stockvaluation.py
Labels: OE

#21854 [IMP] website_event: added two primary buttons (for outlook & gmail)
  addons/website_event/controllers/main.py
  addons/website_event/models/event.py
  addons/website_event/views/event_templates.xml
  addons/website_event_sale/controllers/main.py
Labels: RD, Services

#24496 [FIX] hr_expense: account on expense
  addons/hr_expense/models/hr_expense.py
Labels: OE
