Repository odoo/odoo, pull requests merged in 2018-09, with the labels that each got.

#26693 [FIX] delivery: Error message for unavailable delivery methods
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/delivery_grid.py
Labels: OE

#26601 [FIX] mail_bot: do not crash on user with no email
  addons/mail_bot/models/mail_bot.py
  addons/mail_bot/models/mail_channel.py
Labels: RD, Services

#26738 [FIX] purchase: vendor reference
  addons/purchase/models/account_invoice.py
Labels: RD

#26460 [FIX] l10n_th: withholding taxes
  addons/l10n_th/data/l10n_th_chart_data.xml
Labels: OE

#26157 WIP:[FIX] web: tab selects first many2one entry without triggering sp…
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: OE

#26628 [FIX] web: load more with progressbar load more
  addons/web/static/src/js/views/kanban/kanban_model.js
  addons/web/static/tests/views/kanban_tests.js
Labels: OE

#26745 [FIX] sale_stock: Printing Delivery Order
  addons/sale_stock/report/stock_report_deliveryslip.xml
Labels: OE

#26582 [FIX] web_editor: focus lost with inline editor
  addons/web_editor/static/lib/summernote/src/js/EventHandler.js
  addons/web_editor/static/src/js/backend/fields.js
Labels: OE

#26746 [FIX] sale_timesheet: fixup timesheet cost
  addons/sale_timesheet/models/account.py
Labels: RD

#26676 [FIX] web: ignore default_* on group creation
  addons/web/static/src/js/views/kanban/kanban_model.js
  addons/web/static/tests/views/kanban_tests.js
Labels: OE

#26754 [FIX] web: export field with '/'
  addons/web/controllers/main.py
Labels: OE

#26753 [FIX] website_event: Not possible to edit badges
  addons/website_event/i18n/website_event.pot
  addons/website_event/views/event_views.xml
Labels: OE

#26762 [FIX] web: time display
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/tests/views/calendar_tests.js
Labels: OE

#26761 [FIX] point_of_sale: pricelist
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/models.js
Labels: OE

#26765 [FIX] web_editor: image name
  addons/web_editor/static/src/js/widgets/widgets.js
Labels: OE

#26764 [FIX] web_editor: image name
  addons/web_editor/static/src/js/widgets.js
Labels: OE

#26778 [FIX] base: allow get_template serialization retry
  odoo/addons/base/ir/ir_qweb/qweb.py
Labels: OE

#26755 [FIX] purchase_requisition: datetime convertion
  addons/purchase_requisition/models/purchase_requisition.py
Labels: RD

#26785 [FIX] base: allow get_template serialization retry
  odoo/addons/base/ir/ir_qweb/qweb.py
Labels: OE

#26742 [FIX] web: lock handle when sorting on a different field
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: OE

#26350 [FIX] mail: display icon
  addons/mail/static/src/scss/discuss.scss
Labels: RD

#26802 [FIX] mail: only display errors linked to message of current user
  addons/mail/models/mail_message.py
Labels: RD

#26497 [FIX] mail: Avoid using default value for track fields logging
  addons/mail/models/mail_thread.py
  odoo/models.py
  odoo/tools/misc.py
Labels: RD

#26800 [FIX] sale: Server Error when trying to process card
  addons/sale/models/sale.py
Labels: OE

#26794 [FIX] account: unreconcile cash basis
  addons/account/models/account_move.py
Labels: OE

#26824 [FIX] sale: prevent confirmation of SO
  addons/sale/i18n/sale.pot
  addons/sale/models/sale.py
Labels: OE

#26829 [FIX] point_of_sale: restrict price control
  addons/point_of_sale/static/src/js/screens.js
Labels: OE

#26805 [FIX] base: allow to use abs in views
  odoo/addons/base/ir/ir_ui_view.py
Labels: OE

#26851 [FIX] snailmail: fix cron job name typo
  addons/snailmail/data/snailmail_data.xml
Labels: RD

#26739 [FIX] models: support multiple group by in _read_group_fill_temporal
  odoo/models.py
Labels: RD

#26847 [FIX] website_quote: option product discount report print
  addons/website_quote/report/sale_order_templates.xml
Labels: OE

#26845 [FIX] account: manual reconciliation with tax
  addons/account/static/src/js/reconciliation/reconciliation_model.js
Labels: OE

#26766 [FIX] web_settings_dashboard: give context to search_read planners
  addons/web_settings_dashboard/static/src/js/dashboard.js
  addons/web_settings_dashboard/static/tests/dashboard_tests.js
  addons/web_settings_dashboard/views/dashboard_templates.xml
Labels: OE

#26871 [FIX] sale: analytic account in confirmed state
  addons/sale/views/sale_views.xml
Labels: OE

#26873 [FIX] point_of_sale: mandatory picking type
  addons/point_of_sale/views/pos_config_view.xml
Labels: OE

#26664 [FIX] product: fix UI glitch in prouduct form view under sales tab
  addons/product/views/product_views.xml
Labels: RD

#26872 [FIX] membership: recompute state
  addons/membership/models/partner.py
Labels: OE

#26599 Saas 11.5 fix ajax abort chm
  addons/bus/static/src/js/crosstab_bus.js
Labels: RD

#26879 [IMP] payment: Improved error message for an empty field in payment.acquirer form view
  addons/payment/models/payment_acquirer.py
Labels: OE

#26881 Saas 11.4 duplicate trans pot targets again mat
  odoo/addons/test_translation_import/i18n/fr.po
  odoo/addons/test_translation_import/i18n/test_translation_import.pot
  odoo/tools/translate.py
Labels: RD

#26621 [FIX] models: prevent default_ keys to mess with another model
  addons/mail/models/ir_actions.py
Labels: OE

#26819 [FIX] account: cash basis in statement
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/static/src/js/reconciliation/reconciliation_model.js
Labels: OE

#26887 [FIX] calendar: keep recurring after edited one
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar_recurrent_event_case2.py
Labels: OE

#26901 [FIX] calendar: keep recurring after edited one
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar_recurrent_event_case2.py
Labels: OE

#26909 [FIX] sale_timesheet: Validating an invoice with timesheets
  addons/sale_timesheet/models/account_invoice.py
Labels: OE

#26912 [FIX] *mail_thread: don't modify modified help
  addons/crm/models/crm_lead.py
  addons/hr_expense/models/hr_expense.py
  addons/im_livechat/models/mail_channel.py
  addons/mail/models/mail_thread.py
Labels: OE

#26911 [FIX] *mail_thread: don't modify modified help
  addons/crm/models/crm_lead.py
  addons/hr_expense/models/hr_expense.py
  addons/im_livechat/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/sale/models/sale.py
Labels: OE

#21849 [IMP] account: make it possible to hand over communication
  addons/account/models/account_invoice.py
Labels: Accounting

#26852 Saas 14 fixes dam
  addons/account/i18n/account.pot
  addons/account/models/company.py
Labels: OE

#26943 [FIX] web: revert ignore default_* on group creation
  addons/web/static/src/js/views/kanban/kanban_model.js
  addons/web/static/tests/views/kanban_tests.js
Labels: OE

#26930 [FIX] account: open balance account when partner change
  addons/account/static/src/js/reconciliation/reconciliation_model.js
Labels: OE

#26937 [FIX] sale_stock, stock_dropshipping: ordered qty
  addons/sale_stock/models/sale_order.py
  addons/stock_dropshipping/models/__init__.py
  addons/stock_dropshipping/models/sale.py
  addons/stock_dropshipping/tests/__init__.py
  addons/stock_dropshipping/tests/test_dropship.py
Labels: OE

#26967 remove option to sanitize communication
  addons/account/models/account_invoice.py
  addons/account/models/account_payment.py
  addons/account/models/company.py
  addons/account/models/res_config_settings.py
  addons/account/views/res_config_settings_views.xml
Labels: Accounting, RD

#26897 11.5 seo2 seb
  addons/web/static/src/scss/modal.scss
  addons/website/models/website.py
  addons/website/static/src/js/menu/seo.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/xml/website.seo.xml
  addons/website/views/website_templates.xml
Labels: RD

#26966 [FIX] project: remove group_by from the context
  addons/project/models/project.py
Labels: OE

#26771 [FIX] website: seo add words no freeze
  addons/website/static/src/js/menu/seo.js
Labels: OE

#26940 [FIX] stock_account: return dropship
  addons/stock_account/models/stock.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
Labels: OE

#26991 [FIX] website: AccessError
  addons/website/models/res_config_settings.py
Labels: RD

#26987 [FIX] web: JournalDashboardGraph widget crash Mk.II
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: OE

#26469 [FIX] web: translate "No Data Available" message
  addons/web/static/src/js/views/graph/graph_renderer.js
Labels: OE

#27002 [FIX] crm,sale_crm: split action_mark_won
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/sale_crm/views/crm_lead_views.xml
Labels: RD

#26998 [FIX] l10n_be_intrastat: shipping country
  addons/l10n_be_intrastat/wizard/xml_decl.py
Labels: OE

#26976 [FIX] account: Reconcile a statement with move line from partner
  addons/account/models/account_bank_statement.py
Labels: OE

#27020 [FIX] report_intrastat: delivery address
  addons/report_intrastat/report/report_intrastat_report.py
Labels: OE

#26994 [FIX] point_of_sale: deactivate price change on switch from admin on price control
  addons/point_of_sale/static/src/js/screens.js
Labels: Point of Sale, RD

#27022 [FIX] point_of_sale: toggle the checkbox correctly.
  addons/point_of_sale/views/pos_config_view.xml
Labels: OE

#26744 [FIX] account*, sale*, website: portal: public user not necessarily i…
  addons/account/controllers/mail.py
  addons/account_payment/controllers/payment.py
  addons/account_payment/controllers/portal.py
  addons/portal/controllers/mail.py
  addons/sale/controllers/mail.py
  addons/sale_payment/controllers/payment.py
  addons/sale_payment/controllers/portal.py
  addons/website_event/models/event.py
Labels: OE

#27026 [FIX] website_sale: fallback on partner sales team if undefined on we…
  addons/website_sale/models/website.py
Labels: OE

#26513 [REF] stock: `_action_done` and cache invalidation
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_move2.py
  addons/stock/tests/test_packing_neg.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/tests/test_warehouse.py
  addons/stock/tests/test_wise_operator.py
  addons/stock/wizard/stock_quantity_history.py
  addons/stock_picking_batch/tests/test_batch_picking.py
Labels: RD

#27068 [FIX] tools: import translation file without pot
  odoo/addons/test_translation_import/i18n/dot.csv
  odoo/addons/test_translation_import/i18n/tlh.po
  odoo/addons/test_translation_import/models.py
  odoo/addons/test_translation_import/tests/test_term_count.py
  odoo/tools/translate.py
Labels: Framework, RD

#26969 [FIX] *: adapt calls to _is_superuser
  addons/portal/views/portal_templates.xml
  addons/web/models/ir_http.py
  addons/web_editor/views/iframe.xml
  addons/web_tour/models/ir_http.py
  addons/web_tour/static/src/js/tour_service.js
  addons/website/views/website_templates.xml
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/res_config.py
Labels: RD

#26854 [FIX] stock_landed_costs: do not prorate
  addons/stock_landed_costs/models/stock_landed_cost.py
Labels: OE

#27055 [FIX] stock: extra move in return
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move2.py
Labels: OE

#27056 [FIX] account, sale: Intrastat delivery address
  addons/account/models/account_invoice.py
  addons/sale/models/account_invoice.py
Labels: OE

#27031 [FIX] sale_stock: translate product name
  addons/sale_stock/models/sale_order.py
Labels: OE

#27101 [FIX] hr_attendance : fix kiosk mode quick multi scanning
  addons/hr_attendance/static/src/js/greeting_message.js
  addons/hr_attendance/static/src/js/kiosk_mode.js
Labels: RD

#26928 Avoid costly queries on messages due to moderation system
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/services/chat_manager.js
  addons/mail/static/tests/helpers/mock_server.js
Labels: RD

#27108 [FIX] models: do not copy translations from specified inherited records
  odoo/addons/test_new_api/demo_data.xml
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
Labels: Internationalization, RD

#27126 [FIX] google_drive: current record
  addons/google_drive/static/src/js/gdrive.js
  addons/google_drive/static/tests/gdrive_test.js
Labels: OE

#27000 [IMP] account: improve reconciliation congratulation message
  addons/account/static/src/xml/account_reconciliation.xml
Labels: Accounting, RD

#27095 [FIX] account: dashboard: fix count of number of items to reconcile
  addons/account/models/account_journal_dashboard.py
Labels: Accounting, RD

#27081 [FIX]stock: removed 'completion date' from stock picking form view as…
  addons/stock/views/stock_picking_views.xml
Labels: RD

#27133 [IMP] Generic: Improved tooltip according to business oriented with p…
  addons/account/models/partner.py
  addons/account/models/product.py
  addons/event_sale/models/product.py
  addons/hr_expense/models/product_template.py
  addons/membership/models/partner.py
  addons/point_of_sale/models/product.py
  addons/product/models/product_template.py
  addons/product_email_template/models/product.py
  addons/purchase/models/product.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/sale/models/product_template.py
  addons/stock/models/product.py
  addons/stock/models/res_partner.py
  addons/stock_landed_costs/models/product.py
  addons/website_crm_partner_assign/models/res_partner.py
  addons/website_sale/models/product.py
  addons/website_sale_options/models/product.py
  odoo/addons/base/models/res_partner.py
Labels: RD

#27127 [FIX] hr_attendance : fix kiosk mode - js review
  addons/hr_attendance/static/src/js/greeting_message.js
  addons/hr_attendance/static/src/js/kiosk_mode.js
  addons/hr_attendance/static/tests/hr_attendance_tests.js
Labels: RD

#27162 [IMP] event_sale: add "editable" on SO when removing event_sale
  addons/event_sale/views/sale_order_views.xml
Labels: RD

#27130 [FIX] base: Traceback when uploading a file with no ASCII name
  odoo/addons/base/i18n/base.pot
  odoo/fields.py
Labels: OE

#27054 [stock] Filters not working
  addons/stock_account/views/stock_account_views.xml
Labels: RD

#27134 [FIX] crm: don't change sale team when salesman hasn't got one
  addons/crm/models/crm_lead.py
Labels: RD

#26760 [FIX]mrp: Too large kanban image.
  addons/mrp/views/ir_attachment_view.xml
Labels: RD

#27049 [FIX] payment, payment_sips: compute reference correctly and encode r…
  addons/payment/controllers/portal.py
  addons/payment_sips/controllers/main.py
  addons/payment_sips/models/payment.py
Labels: RD

#27155 [FIX] ir_ui_view: do not check arch twice upon install/upgrade
  odoo/addons/base/models/ir_ui_view.py
  odoo/modules/loading.py
Labels: RD

#27157 [FIX] models: add filter method on access rules
  odoo/models.py
Labels: RD

#27131 [FIX] website_slides: fix bs4 bugs
  addons/website_slides/static/lib/pdfslidesviewer/PDFSlidesViewer.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides.xml
  addons/website_slides/views/website_slides_embed.xml
Labels: RD

#27224 [FIX] point_of_sale: AccessError
  addons/point_of_sale/models/pos_order.py
Labels: OE

#27222 [FIX] mrp: Cost & Structure
  addons/mrp/report/mrp_report_bom_structure.py
Labels: OE

#27227 [FIX] base: perform field reflection in batch
  addons/base_sparse_field/models/models.py
  odoo/addons/base/models/ir_model.py
Labels: RD

#27194 [FIX] payment: always redirect when using wire transfer
  addons/payment/controllers/portal.py
  addons/payment/static/src/js/payment_processing.js
  addons/website_event_sale/static/src/js/website.tour.event_sale.js
  addons/website_sale/static/src/js/website_sale_tour_buy.js
Labels: RD

#27240 [IMP] product,(website_)sale: Product configurator naming/cleanup
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/tests/test_frontend.py
  addons/product/data/product_demo.xml
  addons/product/models/product.py
  addons/product/models/product_attribute.py
  addons/product/models/product_template.py
  addons/product/security/ir.model.access.csv
  addons/product/tests/test_product_attribute_value_config.py
  addons/product/tests/test_variants.py
  addons/product/views/product_attribute_views.xml
  addons/sale/controllers/product_configurator.py
  addons/sale/data/sale_demo.xml
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale/models/sale.py
  addons/sale/security/ir.model.access.csv
  addons/sale/static/src/js/product_configurator_controller.js
  addons/sale/static/src/js/product_configurator_mixin.js
  addons/sale/static/src/js/product_configurator_modal.js
  addons/sale/views/product_attribute_views.xml
  addons/sale/views/sale_product_configurator_templates.xml
  addons/sale/views/sale_views.xml
  addons/sale_management/tests/test_sale_ui.py
  addons/stock/security/ir.model.access.csv
  addons/website_sale/controllers/main.py
  addons/website_sale/data/demo.xml
  addons/website_sale/models/sale_order.py
  addons/website_sale/security/ir.model.access.csv
  addons/website_sale/static/src/js/website_sale_options.js
  addons/website_sale_comparison/data/website_sale_comparison_demo.xml
  addons/website_sale_options/i18n/it.po
  addons/website_sale_options/static/src/js/website_sale.js
Labels: RD

#27280 [FIX] stock_account: visual ok product standard_price
  addons/stock_account/views/product_views.xml
Labels: OE
