Repository odoo/odoo, pull requests merged in 2018-11, with the labels that each got.

#28348 [FIX] sale_timesheet: UOM
  addons/sale_timesheet/models/account.py
Labels: OE

#28311 [FIX] mrp: subproduct price + rounding
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
Labels: RD

#28052 [FIX] account: Fix multi-company/currency in Aged Partner report
  addons/account/report/account_aged_partner_balance.py
Labels: Accounting, RD

#28407 [FIX] mrp: Bom Cost with variants are not displayed properly
  addons/mrp/report/mrp_bom_cost_report_templates.xml
Labels: OE

#25084 Saas 11.3 base admin picture update issue pka
  odoo/addons/base/tests/test_orm.py
  odoo/models.py
Labels: RD

#28463 [CLA] Signature for Ugaitz Olaizola
  doc/cla/individual/ugaitzolaizola.md
Labels: OE

#28189 [FIX] website_sale: performance when creating a cart
  addons/website_sale/models/website.py
Labels: RD

#28577 [FIX] check mp_dirty to avoid repeated orderline rendering
  addons/pos_restaurant/static/src/js/multiprint.js
Labels: 10.0, 11.0, 12.0, Point of Sale, RD

#28605 [FIX] point_of_sale: order selector buttons
  addons/point_of_sale/static/src/css/pos.css
Labels: 10.0, 11.0, 12.0, Point of Sale, RD

#28670 [FIX] product: use product.pricelist in report product_pricelist
  addons/product/report/product_pricelist.py
Labels: RD

#28723 [FIX] auth_signup: Error when sending quotation
  addons/auth_signup/models/res_partner.py
Labels: OE

#28923 [FIX] purchase: es_AR translation typo
  addons/purchase/i18n/es_AR.po
Labels: OE
