Repository odoo/odoo, pull requests merged in 2019-07, with the labels that each got.

#34715 [MERGE] Forward port from 10.0 to saas-14 up to 0ec0a4a32e9
  addons/account/models/partner.py
  odoo/models.py
Labels: RD

#34720 [FIX] website_payment: consider authorized transactions as done
  addons/website_payment/controllers/main.py
Labels: OE

#34745 [FIX] base: revert of 9607f4e801cf4f78eb632e8f603822a891d47a31
  odoo/addons/base/models/res_partner.py
Labels: CI 🤖, RD, seen 🙂

#34894 [MERGE] Forward port of saas-11.3 to 12.0 up to d8072d54acf8
  addons/account/i18n/zh_TW.po
  addons/account_voucher/models/account_voucher.py
  addons/mass_mailing/controllers/main.py
  addons/payment/controllers/portal.py
  addons/stock/models/product.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/website_sale/models/website.py
Labels: CI 🤖, RD, merging 👷, r+ 👌, seen 🙂

#35068 [MERGE] Forward port of saas-12.4 to master up to aadc4a9f0be4
  addons/event_sale/static/src/js/event_configurator_widget.js
  addons/event_sale/views/sale_order_views.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_recruitment_survey/i18n/uk.po
  addons/l10n_at/data/account_tax_data.xml
  addons/l10n_at/data/account_tax_report_data.xml
  addons/lunch/models/lunch_cashmove.py
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/maintenance/i18n/uk.po
  addons/membership/i18n/ca.po
  addons/mrp/i18n/hu.po
  addons/repair/i18n/de.po
  addons/repair/i18n/hu.po
  addons/resource/i18n/nl.po
  addons/sale/i18n/hu.po
  addons/sale/i18n/ro.po
  addons/sale/models/product_template.py
  addons/sale/static/src/js/product_configurator_widget.js
  addons/sale/views/res_config_settings_views.xml
  addons/sale/views/sale_views.xml
  addons/sale_management/i18n/de.po
  addons/sale_management/i18n/hu.po
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_controller.js
  addons/sale_product_configurator/static/src/js/product_configurator_widget.js
  addons/sale_product_configurator/static/src/js/tours/sale_product_configurator.js
  addons/sale_product_configurator/views/assets.xml
  addons/sale_quotation_builder/i18n/de.po
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/i18n/hu.po
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/web/static/tests/views/calendar_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/wysiwyg/plugin/helper.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/src/js/wysiwyg_snippets/wysiwyg_snippets.js
  addons/web_editor/static/tests/wysiwyg_tests.js
  addons/website/i18n/hu.po
  addons/website_customer/i18n/ca.po
  addons/website_event/i18n/ca.po
  addons/website_membership/i18n/ca.po
Labels: RD, error 🙅, merging 👷, seen 🙂
