Repository odoo/odoo, pull requests merged in 2019-01, with the labels that each got.

#29973 [CLA] PlanetaTIC
  doc/cla/corporate/planetatic.md
Labels: merging 👷, seen 🙂

#29672 [FIX] website_sale: make eCommerce animations work in all browsers
  addons/website_sale/static/src/css/website_sale.css
  addons/website_sale/static/src/css/website_sale.sass
Labels: RD, Website

#30269 [IMP] mrp,stock_account: faster computation
  addons/mrp/models/stock_move.py
  addons/stock_account/models/stock.py
Labels: RD

#30402 [FIX] base ir.actions.report order pdfs when attachment_use option selected
  odoo/addons/base/models/ir_actions_report.py
Labels: CI 🤖, OE, merging 👷, r+ 👌
